Repository fluidd-core/fluidd, pull requests merged in 2021-11, with the labels that each got.

#417 l10n: update french translations
  src/locales/fr.yaml
Labels: UI - Translations

#393 Updated Spanish translation
  src/locales/es.yaml
Labels: UI - Translations

#358 Czech translation
  src/locales/cz.yaml
  src/store/config/index.ts
Labels: UI - Translations

#444 Fixed URL in step 5
  docs/installation/fluiddpi.md
Labels: Docs - Change

#443 fix: file system browser selection
  src/components/widgets/filesystem/FileSystemBrowser.vue
Labels: GH - Bug
