Repository fluidd-core/fluidd, pull requests merged in 2022-02, with the labels that each got.

#486 feat: enhanced console filtering
  src/components/layout/AppSettingsNav.vue
  src/components/settings/console/ConsoleFilterDialog.vue
  src/components/settings/console/ConsoleSettings.vue
  src/components/widgets/console/ConsoleCard.vue
  src/locales/en.yaml
  src/store/console/actions.ts
  src/store/console/getters.ts
  src/store/console/index.ts
  src/store/console/mutations.ts
  src/store/console/types.ts
  src/views/Settings.vue
Labels: FR - Enhancement

#507 feat: disable position field if not homed
  src/components/widgets/toolhead/ToolheadPosition.vue
Labels: FR - Enhancement

#489 Feat: Apply_Z_Offset
  src/components/widgets/toolhead/ZHeightAdjust.vue
  src/globals.ts
  src/locales/en.yaml
Labels: FR - Enhancement

#506 i18n: improve and finish german translations
  src/locales/de.yaml
Labels: UI - Translations

#469 Gcode viewer fixes
  src/components/settings/GcodePreviewSettings.vue
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
  src/store/gcodePreview/getters.ts
  src/util/gcode-preview.ts
  src/workers/parseGcode.ts
Labels: FR - Enhancement

#493 chore: Adjust page title order when printing
  src/App.vue
Labels: UI - Change

#436 docs: Add brief instructions on running a local dev server
  docs/development/index.md
Labels: Docs - Change

#496 feat: temperature rate of change
  src/components/ui/AppBtnCollapseGroup.vue
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#483 Feat: Add reset history
  src/api/socketActions.ts
  src/components/widgets/history/PrintHistoryCard.vue
  src/components/widgets/stats/PrinterStatsCard.vue
  src/locales/ar.yaml
  src/locales/cn.yaml
  src/locales/cz.yaml
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/es.yaml
  src/locales/fr.yaml
  src/locales/hu.yaml
  src/locales/it.yaml
  src/locales/ko.yaml
  src/locales/nl.yaml
  src/locales/pt.yaml
  src/locales/ru.yaml
  src/locales/uk.yaml
  src/store/history/actions.ts
  src/store/history/mutations.ts
Labels: FR - Enhancement

#523 feat: show qr-code with api key
  package-lock.json
  package.json
  src/components/settings/auth/ApiKeyDialog.vue
  src/components/ui/AppQrCode.vue
Labels: FR - Enhancement, UI - QoL

#495 feat: pause autoscroll when back scrolling
  src/components/widgets/console/Console.vue
  src/components/widgets/console/ConsoleCard.vue
  src/locales/en.yaml
Labels: FR - Enhancement

#524 fix: improves macro param default value handling
  src/components/ui/AppMacroBtn.vue
Labels: UI - QoL

#525 feat: Add full-screen button to camera view
  src/components/widgets/camera/CameraItem.vue
  src/globals.ts
Labels: FR - Enhancement, UI - Cams, UI - QoL

#522 feat: option to flip console direction
  src/components/widgets/console/Console.vue
  src/components/widgets/console/ConsoleCard.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#452 Allow rotation of camera image
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/widgets/camera/CameraItem.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/cameras/types.ts
Labels: FR - Enhancement, UI - Cams, UI - QoL

#527 feat: TURN_OFF_HEATERS confirmation in temperature presets
  src/components/widgets/thermals/TemperatureCard.vue
  src/locales/de.yaml
  src/locales/en.yaml
Labels: FR - Enhancement, UI - QoL

#531 chore: updates @mdi/js to "^6.5.95"
  package-lock.json
  package.json
  src/globals.ts
Labels: Code - Deps

#530 docs: updates links to Fluidd github org
  docs/configuration/moonraker.md
  docs/configuration/moonraker_conf.md
Labels: Docs - Change

#504 feat: Expanded Service State
  src/api/socketActions.ts
  src/components/common/SystemCommands.vue
  src/components/layout/AppToolsDrawer.vue
  src/globals.ts
  src/locales/en.yaml
  src/mixins/services.ts
  src/store/server/actions.ts
  src/store/server/getters.ts
  src/store/server/mutations.ts
  src/store/server/types.ts
  src/store/socket/actions.ts
Labels: FR - Enhancement

#455 Documentation about configuring multiple cameras
  docs/features/cameras.md
Labels: Docs - Enhancement, GH - Waiting for Feedback

#533 chore: adds commit validation via husky
  .editorconfig
  .husky/commit-msg
  .husky/pre-commit
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: Code - Infrastructure

#537 docs: reflect latest features
  .github/images/preview.png
  .github/images/preview_sliced.png
  docs/assets/images/camera_settings.png
  docs/assets/images/graph.png
  docs/assets/images/preview.png
  docs/assets/images/preview_sliced.png
  docs/features/cameras.md
  docs/features/console.md
Labels: Docs - Change

#543 fix: add missing default for idle fps input
  src/components/settings/cameras/Cameras.vue
  src/store/cameras/index.ts
Labels: GH - Bug, UI - Cams

#544 fix: filename wrap in status window
  src/components/widgets/status/StatusLabel.vue
  src/components/widgets/status/StatusTab.vue
Labels: FR - Enhancement, UI - QoL

#548 Fix: Alias for uncategorized macro
  src/components/widgets/macros/Macros.vue
Labels: GH - Bug
