Repository fluidd-core/fluidd, pull requests merged in 2022-04, with the labels that each got.

#627 fix: fully unload dialogs when not in use
  src/components/common/SystemPrinters.vue
  src/components/layout/AppBar.vue
  src/components/settings/VersionSettings.vue
  src/components/widgets/filesystem/FileNameDialog.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
Labels: GH - Bug, Code - Optimizations

#628 feat: formats weight as human readable
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/plugins/filters.ts
Labels: UI - QoL

#631 Update cn.yaml
  src/locales/cn.yaml
Labels: UI - Translations

#634 feat(i18n-HU): Update Hungarian translation
  src/locales/hu.yaml
Labels: UI - Translations

#636 fix: layout database data handling
  src/store/layout/mutations.ts
Labels: GH - Bug

#633 feat: calculate linear progress
  src/store/printer/getters.ts
Labels: UI - QoL

#610 feat: timelapse browser
  src/api/socketActions.ts
  src/components/layout/AppNavDrawer.vue
  src/components/layout/AppSettingsNav.vue
  src/components/settings/timelapse/TimelapseSettings.vue
  src/components/settings/timelapse/subsettings/CustomParkPositionSettings.vue
  src/components/settings/timelapse/subsettings/ParkExtrudeRetractSettings.vue
  src/components/settings/timelapse/subsettings/ToolheadParkingSettings.vue
  src/components/settings/timelapse/subsettings/modes/HyperlapseSettings.vue
  src/components/ui/AppSlider.vue
  src/components/widgets/filesystem/FilePreviewDialog.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/components/widgets/filesystem/FileSystemMenu.vue
  src/components/widgets/filesystem/FileSystemToolbar.vue
  src/components/widgets/timelapse/TimelapseRenderSettingsDialog.vue
  src/components/widgets/timelapse/TimelapseSettingsCard.vue
  src/components/widgets/timelapse/TimelapseStatusCard.vue
  src/globals.ts
  src/locales/de.yaml
  src/locales/en.yaml
  src/router/index.ts
  src/store/files/getters.ts
  src/store/files/index.ts
  src/store/files/types.ts
  src/store/helpers.ts
  src/store/index.ts
  src/store/socket/actions.ts
  src/store/timelapse/actions.ts
  src/store/timelapse/getters.ts
  src/store/timelapse/index.ts
  src/store/timelapse/mutations.ts
  src/store/timelapse/types.ts
  src/store/types.ts
  src/views/Settings.vue
  src/views/Timelapse.vue
Labels: FR - Enhancement, UI - QoL

#639 chore(i18n): Rework / Update Chinese Language
  src/components/settings/macros/MacroCategories.vue
  src/components/widgets/gcode-preview/GcodePreviewParserProgressDialog.vue
  src/components/widgets/status/StatusTab.vue
  src/components/widgets/toolhead/ToolheadCard.vue
  src/components/widgets/toolhead/ToolheadMoves.vue
  src/locales/cn.yaml
  src/locales/en.yaml
  src/store/config/index.ts
Labels: UI - Translations

#640 feat(i18n-HU): update Hungarian translation
  src/locales/hu.yaml
Labels: UI - Translations

#646 chore: dependency updates
  package-lock.json
  package.json
  src/api/httpClient.ts
Labels: Code - Deps

#645 feat: show live position
  src/components/widgets/toolhead/ToolheadPosition.vue
  src/plugins/socketClient.ts
  src/store/printer/actions.ts
  src/store/printer/index.ts
Labels: FR - Enhancement

#649 fix: show simple editor on mobile
  src/components/widgets/filesystem/FileEditor.vue
  src/components/widgets/filesystem/FileEditorDialog.vue
  src/components/widgets/filesystem/FileEditorTextOnly.vue
  src/util/is-mobile.ts
Labels: GH - Bug

#651 fix: improves macro params default values parsing
  src/components/ui/AppMacroBtn.vue
  src/util/__tests__/gcode-macro-params.spec.ts
  src/util/gcode-macro-params.ts
Labels: GH - Bug
