Repository fluidd-core/fluidd, pull requests merged in 2022-03, with the labels that each got.

#549 fix: emergency stop button outside iphone safe zone
  src/App.vue
Labels: UI - Mobile

#554 docs: moonraker config refactor
  docs/configuration/moonraker.md
  docs/configuration/moonraker_conf.md
Labels: Docs - Change

#558 chore: removes unused vuex-class dependency
  package-lock.json
  package.json
Labels: Code - Deps

#559 fix: typescript typings
  src/plugins/colorSet.ts
  src/plugins/filters.ts
Labels: Code - Optimizations

#560 chore: removes deprecated vue-headful dependency
  package-lock.json
  package.json
  src/App.vue
  src/main.ts
  src/vue-headful.d.ts
Labels: Code - Deps

#562 chore(i18n): improve, fix and finish german translations
  src/locales/de.yaml
Labels: UI - Translations

#563 feat(ui): display localized printer state in printer status card
  src/components/widgets/status/PrinterStatusCard.vue
Labels: UI - QoL

#572 fix: individual object layer count
  src/components/widgets/status/StatusTab.vue
Labels: GH - Bug

#569 Update Hungarian language
  src/locales/hu.yaml
Labels: UI - Translations

#574 fix(i18n): add missing 'cancelled' translation
  src/locales/de.yaml
  src/locales/en.yaml
Labels: GH - Bug, UI - Translations

#575 feat(thermals): display rate of change for all temperature sensors
  src/components/widgets/thermals/TemperatureTargets.vue
Labels: FR - Enhancement

#577 feat(ui): make color picker movable
  src/components/ui/AppColorPicker.vue
  src/components/widgets/outputs/OutputLed.vue
Labels: FR - Enhancement, UI - QoL

#581 chore: updates dependencies
  package-lock.json
  package.json
Labels: Code - Deps

#582 chore: use locked dependency versions on server
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: Code - Infrastructure

#583 fix: auto-determination of base printer
  src/init.ts
Labels: GH - Bug

#584 feat: unsaved editor close confirmations when unloading the page
  src/components/widgets/filesystem/FileEditorDialog.vue
Labels: FR - Enhancement, UI - QoL

#573 chore: fix GitHub release description
  .github/workflows/release.yml
Labels: Code - Infrastructure

#587 fix(i18n-PT): use localized label
  src/store/config/index.ts
Labels: UI - Translations

#589 chore: more typescript typings
  src/components/widgets/toolhead/ExtruderMoves.vue
  src/views/Dashboard.vue
Labels: Code - Optimizations

#588 feat: adds Pressure Advance support
  src/components/widgets/toolhead/PressureAdvanceAdjust.vue
  src/components/widgets/toolhead/Toolhead.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/printer/getters.ts
Labels: UI - QoL

#585 feat(i18n-JA): adds Japanese language
  src/locales/ja.yaml
  src/store/config/index.ts
Labels: UI - Translations

#590 feat: adjustable toolhead move distances
  src/components/settings/ToolheadSettings.vue
  src/components/widgets/toolhead/ToolheadMoves.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/mutations.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#538 feat: show pressure and humidity from sensors
  src/components/widgets/thermals/TemperatureTargets.vue
  src/locales/en.yaml
  src/store/printer/getters.ts
  src/store/printer/types.ts
Labels: FR - Enhancement

#594 feat: add Reset button to File Editor settings
  src/components/settings/FileEditorSettings.vue
Labels: UI - QoL

#593 fix: improves ToolheadSettings rules and validation
  src/components/settings/ToolheadSettings.vue
Labels: Code - Optimizations

#595 chore: drop support for unused browsers
  .browserslistrc
Labels: Code - Optimizations

#591 feat: adds delta support to gcode viewer
  src/components/widgets/gcode-preview/GcodePreview.vue
Labels: FR - Enhancement

#568 feat: support for moonraker socket connection identification
  src/api/socketActions.ts
  src/globals.ts
  src/store/socket/actions.ts
  src/store/socket/index.ts
  src/store/socket/mutations.ts
  src/store/socket/types.ts
Labels: FR - Enhancement

#596 chore: vuetify tree-shaking
  src/plugins/vuetify.ts
  vue.config.js
Labels: Code - Optimizations

#604 fix: allow decimals in slider bound text controls
  src/components/ui/AppSlider.vue
  src/components/widgets/toolhead/PressureAdvanceAdjust.vue
  src/locales/en.yaml
  src/types/vuetify.ts
Labels: GH - Bug

#597 chore: split FileEditor into a separate chunk
  src/components/widgets/filesystem/FileEditor.vue
  src/components/widgets/filesystem/setupMonaco.ts
  src/main.ts
Labels: Code - Optimizations

#601 fix: TouchEvent is not defined on Firefox desktop
  src/components/ui/AppColorPicker.vue
Labels: GH - Bug

#606 fix: Toolhead and ZHeightAdjust layout
  src/components/widgets/toolhead/Toolhead.vue
  src/components/widgets/toolhead/ZHeightAdjust.vue
Labels: GH - Bug, UI - QoL

#613 feat: add full-screen console view
  src/components/layout/AppNavDrawer.vue
  src/components/widgets/console/ConsoleCard.vue
  src/router/index.ts
  src/views/Console.vue
Labels: FR - Enhancement, UI - QoL

#614 fix(i18n-HU): improve Hungarian translations
  src/locales/hu.yaml
Labels: UI - Translations

#615 fix: thermals chart legend selection event
  src/components/widgets/thermals/ThermalChart.vue
Labels: GH - Bug

#616 feat: add full-screen button to the Jobs card
  src/components/widgets/jobs/JobsCard.vue
Labels: UI - QoL

#619 fix: typescript type narrowing
  src/components/widgets/filesystem/FileSystemContextMenu.vue
Labels: Code - Optimizations

#618 Added thumbnail URI encoding
  src/store/helpers.ts
Labels: GH - Bug

#620 feat: graduates g-code previewer to non-beta
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/locales/ar.yaml
  src/locales/cz.yaml
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/es.yaml
  src/locales/hu.yaml
  src/locales/it.yaml
  src/locales/ja.yaml
  src/locales/ko.yaml
  src/locales/ru.yaml
  src/store/layout/index.ts
Labels: UI - QoL
