Repository fluidd-core/fluidd, pull requests merged in 2022-12, with the labels that each got.

#973 fix: temperature chart legend
  src/components/widgets/thermals/TemperatureTargets.vue
  src/components/widgets/thermals/ThermalChart.vue
  src/store/printer/getters.ts
Labels: GH - Bug, UI - QoL

#978 fix: ensures CodeLens is not shown if disabled
  src/components/widgets/filesystem/FileEditor.vue
Labels: GH - Bug

#979 feat(i18n-RU): Update Russian translations
  src/locales/ru.yaml
Labels: UI - Translations

#974 feat: adds Upload and Print button to AppBar
  components.d.ts
  src/components/layout/AppBar.vue
  src/components/layout/AppUploadAndPrintBtn.vue
  src/components/settings/GeneralSettings.vue
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement, UI - QoL

#981 feat: send on enter
  src/components/ui/AppMacroBtn.vue
Labels: UI - QoL

#984 Update moonraker_conf.md
  docs/configuration/moonraker_conf.md
Labels: Docs - Change

#985 fix: add moonraker routes to workbox.navigateFallbackDenylist
  vite.config.ts
Labels: GH - Bug

#982 feat(i18n-HU): update Hungarian language
  src/locales/hu.yaml
Labels: UI - Translations

#986 feat: allow Fluidd to run fully offline
  components.d.ts
  src/App.vue
  src/components/common/RegisterServiceWorker.vue
  src/locales/en.yaml
  vite.config.ts
Labels: FR - Enhancement

#991 fix: check type when filtering prefixed sensors
  src/store/printer/getters.ts
Labels: GH - Bug

#992 fix: mitigates Vuetify bug filtering items ahead
  src/components/widgets/filesystem/FileSystem.vue
Labels: GH - Bug

#995 fix: only validate enabled fields in PresetDialog
  src/components/settings/presets/PresetDialog.vue
Labels: GH - Bug

#448 feat: adds Moonraker Job Queue Support
  package-lock.json
  package.json
  src/api/socketActions.ts
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/components/widgets/job-queue/JobQueue.vue
  src/components/widgets/job-queue/JobQueueBrowser.vue
  src/components/widgets/job-queue/JobQueueBulkActions.vue
  src/components/widgets/job-queue/JobQueueCard.vue
  src/components/widgets/job-queue/JobQueueContextMenu.vue
  src/components/widgets/job-queue/JobQueueToolbar.vue
  src/directives/blur.ts
  src/directives/sortableDataTable.ts
  src/globals.ts
  src/locales/en.yaml
  src/main.ts
  src/store/config/state.ts
  src/store/index.ts
  src/store/jobQueue/actions.ts
  src/store/jobQueue/getters.ts
  src/store/jobQueue/index.ts
  src/store/jobQueue/mutations.ts
  src/store/jobQueue/state.ts
  src/store/jobQueue/types.ts
  src/store/layout/state.ts
  src/store/socket/actions.ts
  src/views/Dashboard.vue
  src/views/Jobs.vue
Labels: FR - Enhancement

#997 fix: fallback to icon when history thumbnail fails
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/status/ReprintTab.vue
  src/globals.ts
  src/store/history/actions.ts
  src/store/history/mutations.ts
Labels: GH - Bug
