Repository fluidd-core/fluidd, pull requests merged in 2022-01, with the labels that each got.

#388 feat: adds optional confirmation for power device toggle
  src/components/common/SystemCommands.vue
  src/components/settings/GeneralSettings.vue
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: UI - QoL

#457 Update Simplified Chinese translation
  src/locales/cn.yaml
Labels: UI - Translations

#475 Fix: Spanish translate file
  src/locales/es.yaml
Labels: UI - Translations

#379 Fix: actual end time calculation
  src/store/printer/getters.ts
Labels: FR - Change

#362 Feat: Date/Time format
  src/components/settings/GeneralSettings.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/status/StatusTab.vue
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: UI - QoL

#478 Feat: make each axis controllable after homing
  src/components/widgets/toolhead/ToolheadMoves.vue
  src/mixins/toolhead.ts
  src/store/printer/getters.ts
Labels: FR - Change, UI - Change

#433 docs: Extra explanation on categories
  docs/features/macros.md
Labels: Docs - Enhancement

#487 Fix: typo Date Time Format
  src/components/settings/GeneralSettings.vue
  src/locales/en.yaml
  src/store/config/index.ts
Labels: GH - Bug, FR - Enhancement

#488 Fix: Z move speed issue
  src/components/widgets/toolhead/ToolheadPosition.vue
Labels: GH - Bug
