Repository fluidd-core/fluidd, pull requests merged in 2022-07, with the labels that each got.

#735 feat(ui): Fit console height to screen size
  package-lock.json
  package.json
  src/components/widgets/console/ConsoleCard.vue
Labels: UI - QoL

#737 fix: no collapsed console in fullscreen mode
  src/components/common/CollapsableCard.vue
Labels: GH - Bug

#736 feat: add icon to shutdown on AppBar
  src/components/layout/AppBar.vue
  src/components/settings/GeneralSettings.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#738 feat: Extended G-Code viewer auto-actions
  src/components/settings/GcodePreviewSettings.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
  src/store/gcodePreview/actions.ts
Labels: FR - Enhancement

#719 feat: allows 4 layout columns in dashboard
  src/App.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/history/PrintHistoryCard.vue
  src/components/widgets/stats/PrinterStatsCard.vue
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/toolhead/ToolheadCard.vue
  src/scss/misc.scss
  src/views/Dashboard.vue
Labels: UI - Change

#742 fix: codelens links for moonraker-telegram-bot
  src/components/widgets/filesystem/setupMonaco.ts
  src/locales/en.yaml
Labels: GH - Bug

#739 feat: device power toggle in top navigation
  src/components/layout/AppBar.vue
  src/components/settings/GeneralSettings.vue
  src/globals.ts
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#743 feat: Support full range of klipper PA scale
  src/components/widgets/toolhead/PressureAdvanceAdjust.vue
Labels: FR - Enhancement

#747 chore: updates GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: Code - Infrastructure

#749 fix: add default authentication source to new users
  src/store/auth/mutations.ts
Labels: GH - Bug

#752 fix(style): light theme AppSwitch
  src/components/ui/AppSwitch.vue
Labels: GH - Bug, UI - Change

#751 docs: update team and funding references
  .github/FUNDING.yml
  docs/README.md
  docs/index.md
Labels: Docs - Change

#755 fix(style): light theme and consistency changes
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/toolhead/ToolheadMoves.vue
  src/components/widgets/toolhead/ToolheadPosition.vue
  src/components/widgets/toolhead/ZHeightAdjust.vue
Labels: UI - QoL

#754 feat: Exclude Objects
  src/components/widgets/exclude-objects/ExcludeObjects.vue
  src/components/widgets/exclude-objects/ExcludeObjectsDialog.vue
  src/components/widgets/gcode-preview/GcodePreview.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/gcodePreview/actions.ts
  src/store/helpers.ts
  src/store/index.ts
  src/store/parts/actions.ts
  src/store/parts/getters.ts
  src/store/parts/index.ts
  src/store/parts/mutations.ts
  src/store/parts/types.ts
  src/store/printer/actions.ts
  src/store/types.ts
Labels: FR - Enhancement

#748 docs: Bring docs up to date for 1.19
  docs/assets/images/auth_login_multisource.png
  docs/assets/images/auth_login_multisource_select.png
  docs/assets/images/auth_trusted.png
  docs/assets/images/automated-updates.png
  docs/assets/images/console.png
  docs/assets/images/exclude_object.png
  docs/assets/images/exclude_object_modal.png
  docs/assets/images/gcode_display_opts.png
  docs/assets/images/gcode_preview.png
  docs/assets/images/gcode_settings.png
  docs/assets/images/layout.png
  docs/assets/images/localization.png
  docs/assets/images/macro_visibility.png
  docs/assets/images/macros1.png
  docs/assets/images/macros2.png
  docs/assets/images/presets.png
  docs/assets/images/preview_sliced.png
  docs/assets/images/print_history.png
  docs/assets/images/print_stats.png
  docs/assets/images/reprint.png
  docs/assets/images/theme.png
  docs/assets/images/thumbnails.png
  docs/authorization/index.md
  docs/configuration/moonraker_conf.md
  docs/customize/hide_outputs.md
  docs/features/gcode_viewer.md
Labels: Docs - Change

#757 fix(README): use preview from docs
  .github/images/preview_sliced.png
  README.md
Labels: Docs - Change

#766 fix: OutputLed working with all types of LEDs
  src/components/widgets/outputs/OutputLed.vue
Labels: GH - Bug

#750 feat(ui): Add FORCE_MOVE support to tool controls
  src/components/settings/ToolheadSettings.vue
  src/components/widgets/toolhead/Toolhead.vue
  src/components/widgets/toolhead/ToolheadCard.vue
  src/components/widgets/toolhead/ToolheadMoves.vue
  src/components/widgets/toolhead/ToolheadPosition.vue
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#770 fix: disable FORCE_MOVE toggle when printing / not ready
  src/components/widgets/toolhead/ToolheadCard.vue
Labels: GH - Bug

#771 feat(i18n-HU): update Hungarian translation
  src/locales/hu.yaml
Labels: UI - Translations

#774 feat: match theme-color with primary-color
  src/App.vue
  vue.config.js
Labels: UI - QoL

#775 feat: Save Config And Restart button visibility toggle
  src/components/layout/AppBar.vue
  src/components/settings/GeneralSettings.vue
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: UI - QoL

#776 chore: updated GitHub Pages dependencies
  docs/Gemfile
  docs/Gemfile.lock
Labels: Code - Infrastructure

#772 docs: proper setup to enable "Exclude Objects"
  docs/features/gcode_viewer.md
Labels: Docs - Enhancement

#777 chore: removes @0x4447/potato from devdependencies
  package-lock.json
  package.json
Labels: Code - Infrastructure

#784 chore: code refactor & cleanup
  src/components/widgets/toolhead/ZHeightAdjust.vue
Labels: Code - Optimizations

#786 fix(i18n): fix FORCE_MOVE capitalization
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/hu.yaml
Labels: UI - Translations

#785 feat: adds new Manual Probe helper dialog
  src/components/common/ManualProbeDialog.vue
  src/components/settings/ToolheadSettings.vue
  src/components/ui/AppBtnCollapseGroup.vue
  src/components/ui/AppBtnGroup.vue
  src/components/widgets/bedmesh/BedMeshControls.vue
  src/components/widgets/toolhead/ToolheadCard.vue
  src/globals.ts
  src/locales/en.yaml
  src/mixins/toolhead.ts
  src/store/config/index.ts
  src/store/config/types.ts
  src/store/printer/getters.ts
  src/store/printer/index.ts
Labels: FR - Enhancement

#790 fix: show current layer in Gcode preview by default
  src/store/gcodePreview/index.ts
Labels: FR - Enhancement

#794 chore: update vue-echarts
  package-lock.json
  package.json
Labels: Code - Deps

#789 chore: improve RootState typings
  src/api/httpClient.ts
  src/api/socketActions.ts
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/system/SystemLoadChart.vue
  src/init.ts
  src/mixins/files.ts
  src/plugins/i18n.ts
  src/plugins/socketClient.ts
  src/router/index.ts
  src/store/auth/actions.ts
  src/store/auth/helpers.ts
  src/store/chart_helpers.ts
  src/store/charts/actions.ts
  src/store/charts/getters.ts
  src/store/console/getters.ts
  src/store/files/actions.ts
  src/store/files/getters.ts
  src/store/helpers.ts
  src/store/index.ts
  src/store/macros/getters.ts
  src/store/mesh/getters.ts
  src/store/notifications/types.ts
  src/store/printer/actions.ts
  src/store/printer/getters.ts
  src/store/types.ts
  src/store/version/getters.ts
Labels: Code - Optimizations

#798 fix: hide sub-navigation if socket not connected
  src/components/layout/AppNavDrawer.vue
Labels: UI - QoL

#797 feat: allow showing Bed Mesh on Dashboard
  src/components/widgets/bedmesh/BedMeshCard.vue
  src/store/layout/index.ts
  src/views/Dashboard.vue
  src/views/Tune.vue
Labels: UI - QoL

#799 fix: corrects moonraker docs link for "include" section
  src/components/widgets/filesystem/setupMonaco.ts
Labels: GH - Bug
