Repository fluidd-core/fluidd, pull requests merged in 2022-09, with the labels that each got.

#857 feat: adds variance to bed mesh chart
  src/components/widgets/bedmesh/BedMeshCard.vue
  src/components/widgets/bedmesh/BedMeshChart.vue
  src/vue-echarts-chunk.ts
Labels: FR - Enhancement, UI - QoL

#858 fix: disable force_move on axis with multiple steppers
  src/components/widgets/toolhead/ToolheadMoves.vue
  src/components/widgets/toolhead/ToolheadPosition.vue
  src/mixins/toolhead.ts
Labels: GH - Bug

#763 docs: remote access using Obico
  docs/configuration/obico_for_remote_access.md
Labels: Docs - Enhancement

#859 fix: pressure advance and acceleration units
  src/components/widgets/limits/PrinterLimits.vue
  src/components/widgets/toolhead/PressureAdvanceAdjust.vue
Labels: GH - Bug, UI - QoL

#861 do not escape label for app-slider
  src/components/ui/AppSlider.vue
Labels: GH - Bug

#862 feat: adjustable thumbnail size
  src/components/ui/AppBtnCollapseGroup.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/filesystem/FileSystemToolbar.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: FR - Enhancement, UI - QoL

#867 fix: Camera iframe width
  src/components/widgets/camera/CameraItem.vue
Labels: GH - Bug, UI - Cams

#868 fix: destroy mjpg camera stream properly
  src/components/widgets/camera/CameraItem.vue
Labels: GH - Bug

#869 fix: only auto-load gcode preview on ongoing print
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
Labels: GH - Bug

#875 feat: iframe camera view aspect ratio
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/widgets/camera/CameraItem.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/cameras/index.ts
  src/store/cameras/types.ts
Labels: FR - Enhancement, UI - Cams, UI - Change

#878 feat: user/device specific layouts
  src/components/common/CollapsableCard.vue
  src/components/layout/AppBar.vue
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/layout/actions.ts
  src/store/layout/getters.ts
  src/views/Dashboard.vue
Labels: FR - Enhancement, UI - QoL, UI - Change

#882 fix: auth/setCurrentUser expects object
  src/store/auth/actions.ts
Labels: GH - Bug

#881 feat: Adds any existing Probe to Endstops card
  src/api/socketActions.ts
  src/components/widgets/endstops/EndStopsCard.vue
  src/globals.ts
  src/store/printer/getters.ts
  src/store/printer/types.ts
Labels: FR - Enhancement, UI - QoL
