Repository fluidd-core/fluidd, pull requests merged in 2022-08, with the labels that each got.

#808 feat: Adds minimum support for crowsnest service
  src/globals.ts
Labels: FR - Enhancement

#800 fix: mitigates console warning
  src/App.vue
  vue.config.js
Labels: GH - Bug

#802 feat: adds new Bed Screws Adjust helper dialog
  src/components/common/BedScrewsAdjustDialog.vue
  src/components/common/ManualProbeDialog.vue
  src/components/settings/ToolheadSettings.vue
  src/components/widgets/toolhead/ToolheadCard.vue
  src/locales/en.yaml
  src/mixins/toolhead.ts
  src/store/config/index.ts
  src/store/config/types.ts
  src/store/printer/getters.ts
  src/store/printer/index.ts
Labels: UI - QoL

#809 fix: Enable vue-echarts auto-resizing
  src/components/ui/AppChart.vue
  src/components/widgets/bedmesh/BedMeshChart.vue
  src/components/widgets/thermals/ThermalChart.vue
Labels: GH - Bug

#811 fix: disable dashboard controls if Klipper is not ready
  src/components/ui/AppMacroBtn.vue
  src/components/ui/AppNamedInput.vue
  src/components/ui/AppSlider.vue
  src/components/ui/AppSwitch.vue
  src/components/widgets/console/Console.vue
  src/components/widgets/console/ConsoleCommand.vue
  src/components/widgets/outputs/OutputFan.vue
  src/components/widgets/toolhead/ZHeightAdjust.vue
Labels: GH - Bug

#816 fix: Correct SVG transformations in GCode Preview
  src/components/widgets/gcode-preview/GcodePreview.vue
Labels: GH - Bug, GH - Waiting for Feedback

#815 fix: adds ACCEL parameter to FORCE_MOVE commands
  src/components/widgets/toolhead/ToolheadMoves.vue
  src/components/widgets/toolhead/ToolheadPosition.vue
Labels: GH - Bug

#818 feat: preheat printer chamber if value provided
  src/components/widgets/filesystem/FileSystem.vue
  src/store/files/types.ts
Labels: FR - Enhancement

#817 feat(ui): update all feature
  src/api/socketActions.ts
  src/components/settings/VersionSettings.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/version/actions.ts
Labels: UI - QoL

#823 fix: delta viewbox regression
  src/components/widgets/gcode-preview/GcodePreview.vue
Labels: GH - Bug

#819 fix: edge case where containers order is incorrect
  src/views/Dashboard.vue
Labels: GH - Bug

#820 fix: dashboard constrained width
  src/scss/misc.scss
  src/views/Dashboard.vue
Labels: FR - Enhancement, UI - QoL

#824 feat: enable context menu in monaco editor
  src/components/widgets/filesystem/FileEditor.vue
  vue.config.js
Labels: UI - QoL

#829 fix: width constraint at root container level
  src/App.vue
  src/router/index.ts
  src/store/config/index.ts
  src/store/config/mutations.ts
  src/store/config/types.ts
  src/views/Dashboard.vue
Labels: GH - Bug

#793 feat: Diagnostics panel
  package-lock.json
  package.json
  src/components/common/CollapsableCard.vue
  src/components/layout/AppBar.vue
  src/components/layout/AppNavDrawer.vue
  src/components/settings/GeneralSettings.vue
  src/components/widgets/diagnostics/DiagnosticsCard.vue
  src/components/widgets/diagnostics/DiagnosticsCardConfigDialog.vue
  src/components/widgets/diagnostics/StateExplorer.vue
  src/components/widgets/diagnostics/config/AxesConfigStep.vue
  src/components/widgets/diagnostics/config/CardConfigStep.vue
  src/components/widgets/diagnostics/config/MetricsCollectorConfig.vue
  src/components/widgets/diagnostics/config/MetricsConfigStep.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/plugins/sandboxedEval.ts
  src/router/index.ts
  src/scss/draggable.scss
  src/store/charts/mutations.ts
  src/store/config/index.ts
  src/store/config/types.ts
  src/store/diagnostics/types.ts
  src/store/layout/index.ts
  src/store/layout/mutations.ts
  src/store/printer/actions.ts
  src/util/get-all-layouts.ts
  src/views/Dashboard.vue
  src/views/Diagnostics.vue
  src/vue-json-viewer.d.ts
Labels: FR - Enhancement, Docs - Needed

#822 fix: check for webassembly support
  src/components/widgets/filesystem/FileEditorDialog.vue
  src/util/is-web-assembly-supported.ts
Labels: GH - Bug

#832 fix: reset G-code Preview state on file overwrite
  src/store/files/actions.ts
Labels: GH - Bug

#835 feat: add optional Chamber Temp column to jobs
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/locales/en.yaml
  src/store/config/index.ts
Labels: UI - QoL

#833 chore: dependency updates
  package-lock.json
  package.json
  src/locales/hu.yaml
  vue.config.js
Labels: Code - Deps

#830 fix: mitigates undefined history errors
  src/components/widgets/status/StatusTab.vue
Labels: GH - Bug

#795 feat(ui): custom stylesheet and background image
  src/App.vue
  src/api/socketActions.ts
  src/mixins/files.ts
  src/store/config/getters.ts
  src/store/files/actions.ts
  src/store/files/getters.ts
  src/store/files/index.ts
  src/store/files/mutations.ts
  src/store/files/types.ts
  src/store/socket/actions.ts
Labels: FR - Enhancement, UI - Change, Docs - Needed

#828 fix: Allow uploading theme files
  src/store/files/getters.ts
Labels: FR - Enhancement

#840 feat(i18n-DE): update German translations
  src/locales/de.yaml
Labels: FR - Enhancement, UI - Translations

#838 partial ES translation updates
  src/locales/es.yaml
Labels: UI - Translations, GH - Waiting for Feedback

#839 chore: migrates "fluidd/cameras" to "webcams"
  src/api/socketActions.ts
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/settings/cameras/Cameras.vue
  src/components/settings/timelapse/TimelapseSettings.vue
  src/components/settings/timelapse/subsettings/CustomParkPositionSettings.vue
  src/components/settings/timelapse/subsettings/ParkExtrudeRetractSettings.vue
  src/components/settings/timelapse/subsettings/ToolheadParkingSettings.vue
  src/components/settings/timelapse/subsettings/modes/HyperlapseSettings.vue
  src/components/widgets/camera/CameraItem.vue
  src/components/widgets/timelapse/TimelapseRenderSettingsDialog.vue
  src/components/widgets/timelapse/TimelapseSettingsCard.vue
  src/components/widgets/timelapse/TimelapseStatusCard.vue
  src/globals.ts
  src/init.ts
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/hu.yaml
  src/locales/ru.yaml
  src/store/cameras/actions.ts
  src/store/cameras/getters.ts
  src/store/cameras/index.ts
  src/store/cameras/mutations.ts
  src/store/cameras/types.ts
  src/store/charts/actions.ts
  src/store/console/actions.ts
  src/store/index.ts
  src/store/layout/actions.ts
  src/store/macros/actions.ts
  src/store/socket/actions.ts
  src/store/types.ts
  src/store/webcams/actions.ts
  src/store/webcams/getters.ts
  src/store/webcams/index.ts
  src/store/webcams/mutations.ts
  src/store/webcams/types.ts
  src/util/is-key-of.ts
  src/util/set-url-query-param.ts
Labels: UI - Cams, Code - Optimizations

#842 fix: ensures containers exist
  src/store/layout/mutations.ts
Labels: GH - Bug

#844 refactor: timelapseBrowser property in FileSystem
  src/components/widgets/filesystem/FileSystem.vue
  src/views/Timelapse.vue
Labels: Code - Optimizations

#845 docs: add Diagnostics panel documentation
  docs/assets/images/adjust_layout.png
  docs/assets/images/diagnostics_collector_config.png
  docs/assets/images/diagnostics_edit_card.png
  docs/assets/images/diagnostics_metrics_explorer.png
  docs/assets/images/side_menu.png
  docs/features/diagnostics.md
Labels: Docs - Enhancement

#847 fix: dispatch even if database creation fails
  src/init.ts
Labels: GH - Bug

#843 feat: Enabling default list of endpoints via config
  public/config.json
  server/config.json
  src/init.ts
  src/util/__tests__/sanitize-endpoint.spec.ts
  src/util/sanitize-endpoint.ts
Labels: FR - Enhancement

#846 docs: add custom theming documentation
  docs/customize/themes.md
Labels: Docs - Enhancement

#848 fix(diagnostics): Metrics Explorer styling
  src/components/widgets/diagnostics/StateExplorer.vue
Labels: GH - Bug

#852 fix: disable dashboard controls if Klipper is not ready
  src/components/widgets/toolhead/ToolheadPosition.vue
Labels: GH - Bug

#854 refactor: webcam related typings
  src/store/cameras/types.ts
  src/store/webcams/types.ts
Labels: Code - Optimizations
