Repository fluidd-core/fluidd, pull requests merged in 2022-11, with the labels that each got.

#939 chore: refactors validation rules
  src/components/common/AddInstanceDialog.vue
  src/components/settings/GcodePreviewSettings.vue
  src/components/settings/GeneralSettings.vue
  src/components/settings/ToolheadSettings.vue
  src/components/settings/auth/UserConfigDialog.vue
  src/components/settings/auth/UserPasswordDialog.vue
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/settings/console/ConsoleFilterDialog.vue
  src/components/settings/console/ConsoleSettings.vue
  src/components/settings/macros/MacroCategories.vue
  src/components/settings/macros/MacroCategoryDialog.vue
  src/components/settings/presets/PresetDialog.vue
  src/components/settings/timelapse/TimelapseSettings.vue
  src/components/settings/timelapse/subsettings/CustomParkPositionSettings.vue
  src/components/settings/timelapse/subsettings/ParkExtrudeRetractSettings.vue
  src/components/settings/timelapse/subsettings/ToolheadParkingSettings.vue
  src/components/settings/timelapse/subsettings/modes/HyperlapseSettings.vue
  src/components/ui/AppSlider.vue
  src/components/widgets/bedmesh/SaveMeshDialog.vue
  src/components/widgets/diagnostics/config/AxesConfigStep.vue
  src/components/widgets/diagnostics/config/CardConfigStep.vue
  src/components/widgets/diagnostics/config/MetricsConfigStep.vue
  src/components/widgets/filesystem/FileNameDialog.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/outputs/OutputFan.vue
  src/components/widgets/thermals/InputTemperature.vue
  src/components/widgets/timelapse/TimelapseRenderSettingsDialog.vue
  src/components/widgets/toolhead/ExtruderMoves.vue
  src/plugins/filters.ts
Labels: Code - Optimizations

#940 feat: use service names provided by Moonraker
  src/components/common/SystemCommands.vue
  src/mixins/services.ts
  src/store/server/getters.ts
  src/store/server/types.ts
Labels: GH - Bug, FR - Enhancement

#942 feat: new AppFocusableContainer component
  components.d.ts
  src/components/ui/AppFocusableContainer.vue
  src/components/widgets/gcode-preview/GcodePreview.vue
Labels: UI - Change

#945 fix(i18n): adds missing 'start service' translation
  src/locales/en.yaml
Labels: GH - Bug, UI - Translations

#946 feat: sort instance list alphabetically
  src/store/config/getters.ts
Labels: FR - Enhancement

#943 chore: use create-vue defaults
  .eslintrc.js
  env.d.ts
  package-lock.json
  package.json
  src/App.vue
  src/components/common/SocketDisconnected.vue
  src/components/layout/AppSettingsNav.vue
  src/components/settings/VersionInformationDialog.vue
  src/components/settings/auth/UserConfigDialog.vue
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/settings/console/ConsoleSettings.vue
  src/components/settings/macros/MacroCategories.vue
  src/components/settings/macros/MacroSettings.vue
  src/components/settings/macros/MacroSettingsDialog.vue
  src/components/settings/presets/PresetDialog.vue
  src/components/widgets/console/Console.vue
  src/components/widgets/console/ConsoleCard.vue
  src/components/widgets/console/ConsoleItem.vue
  src/components/widgets/diagnostics/StateExplorer.vue
  src/components/widgets/filesystem/FileEditorTextOnly.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/macros/Macros.vue
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/timelapse/TimelapseStatusCard.vue
  src/main.ts
  src/plugins/httpClient.ts
  src/qrcode.vue.d.ts
  src/shims-tsx.d.ts
  src/shims-vue.d.ts
  src/store/auth/types.ts
  tsconfig.app.json
  tsconfig.config.json
  tsconfig.json
  tsconfig.vitest.json
  types.d.ts
  vite.config.inject-version.ts
  vite.config.ts
Labels: Code - Infrastructure, Code - Deps, Code - Optimizations

#950 feat: adds extrusion estimations
  components.d.ts
  src/components/widgets/toolhead/ExtruderSelection.vue
  src/components/widgets/toolhead/ExtruderStats.vue
  src/components/widgets/toolhead/Toolhead.vue
  src/locales/en.yaml
Labels: FR - Enhancement

#955 refactor: replaces dayjs with native Intl.* API
  package-lock.json
  package.json
  src/components/layout/AppAnnouncementDismissMenu.vue
  src/components/layout/AppNotificationMenu.vue
  src/components/settings/GeneralSettings.vue
  src/components/settings/VersionInformationDialog.vue
  src/components/widgets/console/ConsoleItem.vue
  src/components/widgets/diagnostics/DiagnosticsCard.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/status/ReprintTab.vue
  src/components/widgets/status/StatusTab.vue
  src/components/widgets/thermals/ThermalChart.vue
  src/globals.ts
  src/locales/en.yaml
  src/main.ts
  src/plugins/__tests__/filters.spec.ts
  src/plugins/dayjs.ts
  src/plugins/filters.ts
  src/plugins/i18n.ts
  src/store/auth/actions.ts
  src/store/charts/getters.ts
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/version/getters.ts
  tests/unit/setup.ts
Labels: FR - Enhancement, Code - Optimizations

#957 fix: sort temperature sensors by type and name
  src/store/printer/getters.ts
Labels: FR - Enhancement

#961 fix: extrusion estimation spacing
  src/locales/en.yaml
Labels: GH - Bug

#962 style: alternative alignment for ExtruderStats
  src/components/widgets/toolhead/ExtruderStats.vue
  src/components/widgets/toolhead/Toolhead.vue
Labels: UI - QoL

#963 chore: check for circular references on build
  .github/workflows/build.yml
  package-lock.json
  package.json
  src/components/settings/GeneralSettings.vue
  src/globals.ts
  src/plugins/i18n.ts
  src/router/index.ts
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/files/types.metadata.ts
  src/store/files/types.ts
  src/store/history/types.ts
Labels: Code - Infrastructure, Code - Optimizations

#965 style: improves ExcludeObjectsDialog states visibility
  src/components/widgets/exclude-objects/ExcludeObjectsDialog.vue
Labels: UI - QoL

#964 style: improves G-Code Previewer states visibility
  src/components/widgets/exclude-objects/ExcludeObjects.vue
Labels: UI - QoL
