Repository fluidd-core/fluidd, pull requests merged in 2022-05, with the labels that each got.

#652 fix: increase PA precision to 0.001
  src/components/widgets/toolhead/PressureAdvanceAdjust.vue
Labels: UI - QoL

#654 fix: AppSlider incorrect state
  src/components/ui/AppSlider.vue
  src/components/widgets/outputs/OutputFan.vue
Labels: GH - Bug

#655 fix: show temp item as selected by default
  src/components/widgets/thermals/TemperatureTargets.vue
Labels: GH - Bug, UI - QoL

#660 fix: show temp item as selected by default (cont.)
  src/components/widgets/thermals/TemperatureTargets.vue
Labels: GH - Bug, UI - QoL

#663 feat(i18n-HU): update Hungarian translation
  src/locales/hu.yaml
Labels: FR - Enhancement, UI - Translations

#665 feat: adds Codelens and code folding support
  src/components/widgets/filesystem/setupMonaco.ts
  src/locales/cn.yaml
  src/locales/de.yaml
  src/locales/en.yaml
  src/monaco/language/klipper-config.tmLanguage.json
  src/util/get-vue-app.ts
  vue.config.js
Labels: UI - QoL

#661 fix: console auto-scrolling and flipped layout
  src/components/widgets/console/Console.vue
  src/components/widgets/console/ConsoleCard.vue
Labels: GH - Bug

#667 chore: updates Klipper textmate language definition
  src/monaco/language/klipper-config.tmLanguage.json
Labels: Code - Optimizations

#664 docs: manual build/installation instructions
  docs/installation/manual.md
Labels: Docs - Enhancement

#676 fix(style): light theme fixes/improvements
  src/components/layout/AppNotificationMenu.vue
  src/components/widgets/camera/CameraItem.vue
  src/components/widgets/filesystem/FileEditorTextOnly.vue
  src/components/widgets/status/ReprintTab.vue
  src/scss/file-system.scss
Labels: GH - Bug, UI - QoL

#668 fix: job card history metadata race condition
  src/store/history/actions.ts
Labels: GH - Bug

#678 feat: clear console
  src/components/widgets/console/ConsoleCard.vue
  src/store/console/actions.ts
  src/store/console/getters.ts
  src/store/console/index.ts
  src/store/console/mutations.ts
  src/store/console/types.ts
Labels: FR - Enhancement

#679 fix: allow omit 0 units in gcode number parsing
  src/workers/parseGcode.ts
Labels: GH - Bug

#683 fix: clear "follow progress" if not correct file printing
  src/components/widgets/gcode-preview/GcodePreviewControls.vue
Labels: GH - Bug

#680 feat: replaces Keyboard Shortcuts with Command Palette
  src/components/common/KeyboardShortcutsDialog.vue
  src/components/widgets/filesystem/FileEditor.vue
  src/components/widgets/filesystem/FileEditorDialog.vue
  src/globals.ts
  src/locales/ar.yaml
  src/locales/cn.yaml
  src/locales/cz.yaml
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/es.yaml
  src/locales/fr.yaml
  src/locales/hu.yaml
  src/locales/it.yaml
  src/locales/ja.yaml
  src/locales/ko.yaml
  src/locales/nl.yaml
  src/locales/pt.yaml
  src/locales/ru.yaml
  src/locales/uk.yaml
Labels: UI - QoL

#682 feat: highlight links in warning messages
  src/components/common/AppWarnings.vue
  src/util/link-external-urls.ts
Labels: UI - QoL

#685 fix(i18n-FR): fix typo in French translation
  src/locales/fr.yaml
Labels: UI - Translations

#686 fix: timelapse custom park position
  src/components/settings/timelapse/subsettings/CustomParkPositionSettings.vue
Labels: GH - Bug

#687 feat: add toggles for relative humidity / barometric pressure
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: FR - Enhancement, UI - QoL

#688 chore: temporary fix for release pipeline
  .github/workflows/release.yml
Labels: Code - Infrastructure

#692 fix: code editor folding
  src/components/widgets/filesystem/setupMonaco.ts
Labels: GH - Bug

#694 fix: hide Pressure Advance if no default extruder stepper set
  src/components/widgets/toolhead/Toolhead.vue
Labels: GH - Bug

#695 fix: AppSlider mobile lock disabling
  src/components/ui/AppSlider.vue
Labels: GH - Bug

#696 fix(layout): move gcode controls to dropdown; fix vertical layout
  src/components/widgets/gcode-preview/GcodePreview.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/gcode-preview/GcodePreviewControls.vue
Labels: UI - Change

#699 docs(cameras): refactor configuration instructions
  docs/features/cameras.md
Labels: Docs - Change

#702 feat(i18n-HU): update Hungarian translation
  src/locales/hu.yaml
Labels: UI - Translations
