Repository fluidd-core/fluidd, pull requests merged in 2022-10, with the labels that each got.

#890 fix: check stepper_z exists before applying z_offset
  src/components/widgets/toolhead/ZHeightAdjust.vue
Labels: GH - Bug

#887 fix: FileSystemBrowser icon size and resolution
  src/components/widgets/filesystem/FileSystemBrowser.vue
Labels: UI - QoL

#896 fix: allow initial layer in GcodePreviewCard
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
Labels: GH - Bug

#895 style: consistent margins across all card buttons
  src/components/widgets/bedmesh/BedMeshCard.vue
  src/components/widgets/console/ConsoleCard.vue
  src/components/widgets/endstops/EndStopsCard.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/jobs/JobsCard.vue
  src/components/widgets/system/McuCard.vue
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/thermals/TemperaturePresetsMenu.vue
Labels: UI - Change

#894 feat: gcode preview autozoom
  src/components/widgets/gcode-preview/GcodePreview.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/globals.ts
  src/store/config/index.ts
  src/store/config/types.ts
  src/store/gcodePreview/getters.ts
Labels: FR - Enhancement, UI - QoL

#891 feat: larger thumbnail preview
  src/components/widgets/filesystem/FilePreviewDialog.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/locales/en.yaml
  src/store/files/types.ts
Labels: FR - Enhancement, UI - QoL

#898 fix: Exclude Object not reacting to mobile inputs
  src/components/widgets/exclude-objects/ExcludeObjects.vue
Labels: GH - Bug

#899 chore: use latest changelog-reader-action
  .github/workflows/release.yml
Labels: Code - Infrastructure

#900 chore: removes duplicate auto-complete entries
  src/store/console/getters.ts
Labels: Code - Optimizations

#901 feat: single white channel led control
  src/components/ui/AppColorPicker.vue
Labels: UI - QoL

#903 feat: use layer info from print_stats if available
  src/components/widgets/status/StatusTab.vue
  src/store/printer/getters.ts
Labels: FR - Enhancement

#905 chore: only request oneshot token when required
  src/mixins/files.ts
Labels: Code - Optimizations

#906 feat: adds missing translation keys
  src/components/layout/AppUserMenu.vue
  src/components/settings/VersionStatus.vue
  src/components/ui/AppCardDrag.vue
  src/components/ui/AppMacroBtn.vue
  src/components/widgets/bedmesh/BedMeshControls.vue
  src/components/widgets/filesystem/FilePreviewDialog.vue
  src/components/widgets/filesystem/FileSystemBulkActions.vue
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/views/Login.vue
  src/views/NotFound.vue
Labels: UI - Translations

#909 feat(i18n-HU): update Hungarian language
  src/locales/hu.yaml
Labels: FR - Enhancement, UI - Translations

#880 feat(i18n-JA): update Japanese language
  src/locales/ja.yaml
Labels: UI - Translations

#911 fix: disable controls if Klipper not ready
  src/components/ui/AppBtnCollapseGroup.vue
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/views/Tune.vue
Labels: GH - Bug

#913 style: open fullscreen thumbnails on thumbnail click
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/locales/en.yaml
  src/locales/hu.yaml
Labels: FR - Enhancement, UI - QoL

#914 chore: dependency updates
  package-lock.json
  package.json
Labels: Code - Deps

#915 feat: uses macro description as button tooltip
  src/components/ui/AppMacroBtn.vue
  src/components/widgets/macros/Macros.vue
Labels: UI - QoL

#917 fix: sort the manual probe offsets descending
  src/components/common/ManualProbeDialog.vue
Labels: GH - Bug

#918 style: move macro tooltips to the top of the buttons
  src/components/widgets/macros/Macros.vue
Labels: UI - QoL

#919 chore: dependency updates
  package-lock.json
  package.json
  src/vue-inline-svg.d.ts
Labels: Code - Deps

#921 fix(console): console no longer loses scroll attachment on multiple M118
  src/components/widgets/console/Console.vue
Labels: GH - Bug

#923 Replaces static error messages with translations
  src/components/settings/GcodePreviewSettings.vue
  src/components/settings/ToolheadSettings.vue
  src/components/settings/cameras/CameraConfigDialog.vue
Labels: GH - Bug, UI - QoL

#920 chore: migrates to vitejs
  .browserslistrc
  .eslintignore
  .eslintrc.js
  .gitignore
  README.md
  babel.config.js
  components.d.ts
  cypress.json
  index.html
  jest.config.js
  package-lock.json
  package.json
  public/index.html
  src/.editorconfig
  src/components/_globals.ts
  src/components/common/ManualProbeDialog.vue
  src/components/layout/AppBar.vue
  src/components/layout/AppNotificationMenu.vue
  src/components/settings/VersionInformationDialog.vue
  src/components/ui/AppBtnGroup.vue
  src/components/ui/AppChart.vue
  src/components/ui/AppCodeView.vue
  src/components/ui/AppColorPicker.vue
  src/components/ui/AppNavItem.vue
  src/components/ui/AppSlider.vue
  src/components/widgets/bedmesh/BedMeshChart.vue
  src/components/widgets/filesystem/FileEditor.vue
  src/components/widgets/filesystem/FileEditorDialog.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/filesystem/setupMonaco.ts
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/outputs/OutputFan.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/components/widgets/thermals/ThermalChart.vue
  src/consola.ts
  src/main.ts
  src/mixins/state.ts
  src/plugins/i18n.ts
  src/plugins/vite-plugin-inject-version.ts
  src/plugins/vuetify.ts
  src/plugins/workbox.ts
  src/registerServiceWorker.ts
  src/router/index.ts
  src/scss/draggable.scss
  src/scss/global.scss
  src/scss/misc.scss
  src/shims-vue.d.ts
  src/store/gcodePreview/actions.ts
  src/store/gcodePreview/mutations.ts
  src/store/gcodePreview/types.ts
  src/store/index.ts
  src/types/index.ts
  src/views/FullscreenCamera.vue
  src/workers/parseGcode.ts
  src/workers/parseGcode.worker.ts
  tests/unit/setup.ts
  tsconfig.json
  vite.config.ts
  vue.config.js
Labels: Code - Infrastructure

#927 fix: stop slider animation on navigating to page
  src/components/ui/AppSlider.vue
Labels: GH - Bug

#930 fix: show html formatted welcome message
  src/views/Login.vue
Labels: GH - Bug

#929 chore: resolve circular references
  src/api/auth.api.ts
  src/api/httpClient.ts
  src/api/httpClientActions.ts
  src/api/socketActions.ts
  src/components/common/AddInstanceDialog.vue
  src/components/settings/VersionSettings.vue
  src/components/settings/auth/UserPasswordDialog.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/status/StatusTab.vue
  src/globals.ts
  src/init.ts
  src/main.ts
  src/mixins/files.ts
  src/plugins/httpClientPlugin.ts
  src/plugins/socketClient.ts
  src/store/auth/actions.ts
  src/store/auth/helpers.ts
  src/store/cameras/actions.ts
  src/store/chart_helpers.ts
  src/store/config/getters.ts
  src/store/helpers.ts
  src/store/printer/actions.ts
  src/store/socket/actions.ts
  src/store/version/actions.ts
  src/store/version/index.ts
  src/store/version/mutations.ts
  src/store/version/types.ts
Labels: Code - Optimizations

#932 chore: move forceMove, extrudeSpeed, extrudeLength state to store
  src/components/widgets/toolhead/ExtruderMoves.vue
  src/components/widgets/toolhead/Toolhead.vue
  src/components/widgets/toolhead/ToolheadCard.vue
  src/components/widgets/toolhead/ToolheadMoves.vue
  src/components/widgets/toolhead/ToolheadPosition.vue
  src/store/config/index.ts
  src/store/config/types.ts
Labels: Code - Optimizations
