Repository fluidd-core/fluidd, pull requests merged in 2022-06, with the labels that each got.

#706 feat: moves MCU info to separate panel
  src/components/widgets/system/McuCard.vue
  src/components/widgets/system/McuConstantsDialog.vue
  src/components/widgets/system/SystemOverviewCard.vue
  src/globals.ts
  src/locales/de.yaml
  src/locales/en.yaml
  src/plugins/filters.ts
  src/store/printer/types.ts
  src/views/System.vue
Labels: UI - QoL

#705 Update Traditional Chinese language pack.
  src/locales/zh-HK.yaml
  src/store/config/index.ts
Labels: UI - Translations

#708 feat(i18n-DE): update German translations
  src/locales/de.yaml
  src/locales/en.yaml
Labels: UI - Translations

#709 feat: keep icon buttons visible on mobile view
  src/components/ui/AppBtnCollapseGroup.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/thermals/TemperatureCard.vue
Labels: UI - QoL, UI - Mobile

#714 feat: moonraker-telegram-bot config and service mapping
  src/globals.ts
Labels: FR - Enhancement

#717 fix: mitigates network error with latest Axios
  src/api/httpClient.ts
Labels: GH - Bug

#716 feat: adds setting to toggle Codelens visibility
  src/components/settings/FileEditorSettings.vue
  src/components/widgets/filesystem/FileEditor.vue
  src/components/widgets/filesystem/FileEditorDialog.vue
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
Labels: UI - QoL

#712 docs: remove wrong http:// protocol from ssh instructions
  docs/installation/fluiddpi.md
Labels: Docs - Enhancement

#718 fix: show absolute/relative positioning controls
  src/components/widgets/toolhead/ToolheadPosition.vue
  src/globals.ts
  src/locales/en.yaml
Labels: UI - QoL

#609 feat: fullscreen camera page
  src/components/settings/cameras/Cameras.vue
  src/components/widgets/camera/CameraItem.vue
  src/globals.ts
  src/locales/en.yaml
  src/router/index.ts
  src/store/config/index.ts
  src/store/config/types.ts
  src/views/FullscreenCamera.vue
Labels: FR - Enhancement, UI - Cams

#720 fix: disable absolute/relative positioning controls while printing
  src/components/widgets/toolhead/ToolheadPosition.vue
Labels: GH - Bug

#722 fix: disable positioning mode buttons when klippy is not ready
  src/components/widgets/toolhead/ToolheadPosition.vue
Labels: GH - Bug

#721 feat: ldap authentication support
  src/api/auth.api.ts
  src/components/layout/AppUserMenu.vue
  src/components/settings/auth/AuthSettings.vue
  src/locales/en.yaml
  src/store/auth/actions.ts
  src/store/auth/types.ts
  src/views/Login.vue
Labels: FR - Enhancement

#715 docs: add LDAP instructions
  docs/authorization/index.md
Labels: Docs - Enhancement

#723 fix: LED controls behavior
  src/components/ui/AppColorPicker.vue
  src/components/widgets/outputs/OutputItem.vue
  src/components/widgets/outputs/OutputLed.vue
  src/components/widgets/outputs/Outputs.vue
  src/store/printer/getters.ts
  src/store/printer/types.ts
Labels: GH - Bug

#724 fix: console error from LDAP auth changes
  src/components/layout/AppUserMenu.vue
Labels: GH - Bug

#728 fix: check for root available before listing files
  src/store/history/actions.ts
Labels: GH - Bug

#731 fix: gcode preview initial layout
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
Labels: GH - Bug, UI - QoL

#734 fix: nginx 502 error when restarting moonraker
  src/api/httpClient.ts
Labels: GH - Bug

#726 feat: adds Save Config & Restart button
  src/components/layout/AppBar.vue
  src/components/layout/AppNotificationMenu.vue
  src/components/layout/AppSaveConfigAndRestartBtn.vue
  src/components/layout/AppUserMenu.vue
  src/components/settings/GeneralSettings.vue
  src/components/settings/PendingChangesDialog.vue
  src/components/widgets/bedmesh/BedMeshControls.vue
  src/locales/en.yaml
  src/store/config/index.ts
  src/store/config/types.ts
  src/store/printer/getters.ts
  src/store/printer/index.ts
Labels: UI - QoL
