Repository fluidd-core/fluidd, pull requests merged in 2023-11, with the labels that each got.

#1223 feat: adds new Screws Tilt Adjust helper dialog
  components.d.ts
  src/components/common/BedScrewsAdjustDialog.vue
  src/components/common/ScrewsTiltAdjustDialog.vue
  src/components/settings/ToolheadSettings.vue
  src/components/widgets/bedmesh/BedMeshControls.vue
  src/components/widgets/toolhead/ToolheadCard.vue
  src/globals.ts
  src/locales/en.yaml
  src/mixins/toolhead.ts
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/printer/actions.ts
  src/store/printer/getters.ts
  src/store/printer/mutations.ts
  src/store/printer/state.ts
  src/store/printer/types.ts
Labels: FR - Enhancement

#1228 chore: add funding link to org
  .github/FUNDING.yml
Labels: Code - Infrastructure

#1230 feat: adds origin to GcodePreview
  src/components/settings/GcodePreviewSettings.vue
  src/components/widgets/gcode-preview/GcodePreview.vue
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#1229 chore: adds LDO sponsorship details
  README.md
  docs/assets/images/logo_ldo.svg
  docs/sponsors/index.md
Labels: Docs - Change

#1232 fix(style): pad navigation drawer bottom on mobile view
  src/components/layout/AppNavDrawer.vue
Labels: GH - Bug, UI - Mobile

#1208 chore(i18n): translations update from hosted Weblate
  src/locales/de.yaml
  src/locales/es.yaml
  src/locales/pl.yaml
  src/locales/pt.yaml
Labels: UI - Translations

#1233 feat(i18n-HU): Update Hungarian translations
  src/locales/hu.yaml
Labels: UI - Translations

#1235 fix: corrects order of e-charts dimensions
  src/components/widgets/bedmesh/BedMeshCard.vue
  src/components/widgets/bedmesh/BedMeshChart.vue
  src/util/transform-mesh.ts
Labels: GH - Bug

#1242 feat: use full bed dimensions on bed mesh preview
  src/components/widgets/bedmesh/BedMeshChart.vue
Labels: GH - Bug

#1245 feat: adds WebRTC (go2rtc) support
  docs/features/cameras.md
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/widgets/camera/CameraItem.vue
  src/components/widgets/camera/services/WebrtcGo2RtcCamera.vue
  src/locales/en.yaml
  src/store/cameras/types.ts
Labels: UI - Cams

#1250 fix: disable console timestamps text wrap
  src/components/widgets/console/ConsoleItem.vue
Labels: GH - Bug
