Repository fluidd-core/fluidd, pull requests merged in 2023-12, with the labels that each got.

#1244 chore: updates to Vite 5
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/settings/ThemeSettings.vue
  tsconfig.json
  vite.config.ts
Labels: Code - Infrastructure

#1248 feat: Adds toolhead circle style controls
  src/components/settings/ToolheadSettings.vue
  src/components/widgets/toolhead/Toolhead.vue
  src/components/widgets/toolhead/ToolheadControlCircle.vue
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#1255 feat: Siboor theme
  public/config.json
  public/logo_siboor.svg
  server/config.json
Labels: FR - Enhancement

#1256 feat: Peopoly theme
  public/config.json
  public/logo_peopoly.svg
  server/config.json
Labels: FR - Enhancement

#1240 chore(i18n): translations update from hosted Weblate
  src/locales/de.yaml
  src/locales/es.yaml
  src/locales/pl.yaml
  src/locales/pt.yaml
Labels: UI - Translations

#1263 feat: highlight active tool
  src/components/widgets/toolhead/ToolChangeCommands.vue
Labels: FR - Enhancement

#1262 feat: adds Prompt Dialog support
  components.d.ts
  src/App.vue
  src/components/common/ActionCommandPromptDialog.vue
  src/store/console/actions.ts
  src/store/console/mutations.ts
  src/store/console/state.ts
  src/store/console/types.ts
Labels: FR - Enhancement

#1260 feat: adds minimum_cruise_ratio support
  src/components/widgets/limits/PrinterLimits.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/printer/actions.ts
  src/store/printer/state.ts
Labels: FR - Enhancement

#1267 feat: Prusa theme
  public/config.json
  public/logo_prusa.svg
  server/config.json
Labels: FR - Enhancement

#1239 docs: Add information about the translation platform
  docs/development/localization.md
  docs/features/localization.md
Labels: Docs - Enhancement

#1268 chore(i18n): translations update from hosted Weblate
  src/locales/de.yaml
Labels: UI - Translations

#1246 feat(i18n-HU): Update Hungarian translations
  src/locales/hu.yaml
Labels: UI - Translations

#1264 feat: adds dev container support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.default.json
  .vscode/tasks.json
Labels: Code - Infrastructure

#1272 feat: copy bed mesh into clipboard as image
  src/components/widgets/bedmesh/BedMeshCard.vue
  src/components/widgets/bedmesh/BedMeshChart.vue
  src/globals.ts
  src/locales/en.yaml
  src/locales/fr.yaml
Labels: FR - Enhancement

#1273 feat(i18n-nl): Update Dutch translations
  src/locales/nl.yaml
Labels: UI - Translations

#1278 feat: add feature to filter moonraker backup files
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemFilterMenu.vue
  src/locales/en.yaml
  src/store/files/getters.ts
  src/store/files/types.ts
Labels: FR - Enhancement

#1279 feat: new SVG assets for circle toolhead controls
  src/components/widgets/toolhead/ToolheadControlCircle.vue
  src/components/widgets/toolhead/ToolheadControlCross.vue
Labels: FR - Enhancement, UI - Change

#1281 fix: makes print cooling fan optional
  src/store/printer/state.ts
  src/views/Dashboard.vue
Labels: GH - Bug

#1287 fix: reset default move distance when availables change
  src/components/settings/ToolheadSettings.vue
  src/components/widgets/toolhead/ToolheadControlCross.vue
Labels: GH - Bug

#1288 chore(i18n): translations update from hosted Weblate
  src/locales/ko.yaml
  src/locales/pt.yaml
Labels: UI - Translations
