Repository fluidd-core/fluidd, pull requests merged in 2023-06, with the labels that each got.

#1106 Update Chinese translation
  src/locales/zh-CN.yaml
Labels: UI - Translations

#1107 feat: adds WebRTC (camera-streamer) support
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/widgets/camera/CameraItem.vue
  src/locales/en.yaml
  src/store/cameras/types.ts
Labels: FR - Enhancement, UI - Cams

#1108 feat(i18n-RU): Update Russian translations
  src/locales/ru.yaml
Labels: UI - Translations

#1109 feat: Kingroon theme
  public/config.json
  public/logo_kingroon.svg
  server/config.json
Labels: FR - Enhancement

#1112 feat(i18n-PL): adds Polish translations
  src/globals.ts
  src/locales/pl.yaml
Labels: UI - Translations
