Repository fluidd-core/fluidd, pull requests merged in 2023-07, with the labels that each got.

#1116 feat(i18n-PL): update Polish translations
  src/locales/pl.yaml
Labels: UI - Translations

#1128 fix: don't show gcode load dialog if canceled
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/mixins/files.ts
Labels: GH - Bug

#1121 feat(i18n-HU): update Hungarian translations
  src/locales/hu.yaml
Labels: UI - Translations

#1126 feat(i18n-PL): update Polish translations
  src/locales/pl.yaml
Labels: UI - Translations

#1125 feat(i18n-AF): New Afrikaans locale added
  src/globals.ts
  src/locales/af.yaml
Labels: UI - Translations

#1129 refactor: move each camera to its own component
  src/components/widgets/camera/CameraItem.vue
  src/components/widgets/camera/services/HlsstreamCamera.vue
  src/components/widgets/camera/services/IframeCamera.vue
  src/components/widgets/camera/services/IpstreamCamera.vue
  src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue
  src/components/widgets/camera/services/MjpegstreamerCamera.vue
  src/components/widgets/camera/services/WebrtcCamerastreamerCamera.vue
  src/dynamicImports.ts
  src/mixins/camera.ts
Labels: Code - Optimizations
