Repository fluidd-core/fluidd, pull requests merged in 2023-03, with the labels that each got.

#1051 feat: adds logs rollover support
  components.d.ts
  src/api/socketActions.ts
  src/components/common/RolloverLogsDialog.vue
  src/components/widgets/system/SystemOverviewCard.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/server/actions.ts
Labels: FR - Enhancement

#1052 feat: adds Pause at Layer support
  src/components/widgets/status/PauseAtLayerDialog.vue
  src/components/widgets/status/PauseResumeBtn.vue
  src/components/widgets/status/StatusControls.vue
  src/locales/en.yaml
  src/mixins/state.ts
  src/store/macros/getters.ts
  src/store/macros/types.ts
  src/store/printer/actions.ts
  src/store/printer/getters.ts
Labels: FR - Enhancement

#1055 fix(diagnostics): fix card icon selection
  src/components/widgets/diagnostics/config/CardConfigStep.vue
Labels: GH - Bug

#1054 docs: Adding OctoEverywhere to the docs
  docs/configuration/octoeverywhere_free_remote_access.md
Labels: Docs - Enhancement

#1056 feat: live printing bed mesh changes
  src/components/layout/AppSaveConfigAndRestartBtn.vue
  src/components/widgets/bedmesh/BedMeshControls.vue
  src/locales/ar.yaml
  src/locales/cs.yaml
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/es.yaml
  src/locales/fr.yaml
  src/locales/hu.yaml
  src/locales/it.yaml
  src/locales/ja.yaml
  src/locales/ko.yaml
  src/locales/nl.yaml
  src/locales/pt.yaml
  src/locales/ru.yaml
  src/locales/uk.yaml
  src/locales/zh-CN.yaml
  src/locales/zh-HK.yaml
  src/store/mesh/getters.ts
  src/store/mesh/types.ts
  src/store/printer/state.ts
  src/util/transform-mesh.ts
Labels: FR - Enhancement, Code - Optimizations

#1057 feat: adds toggle for gas resistance
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/printer/getters.ts
  src/store/printer/types.ts
Labels: FR - Enhancement

#1060 feat: adds filters to gcodes and timelapse roots
  src/components/widgets/filesystem/FileSystemFilterMenu.vue
  src/components/widgets/filesystem/FileSystemToolbar.vue
  src/store/files/getters.ts
Labels: FR - Enhancement

#1061 fix: use Lithuanian "lt" for ISO-8601 formats
  src/globals.ts
  src/plugins/__tests__/filters.spec.ts
Labels: GH - Bug

#1062 style: consolidate menu styling
  src/components/layout/AppUserMenu.vue
  src/components/ui/AppColumnPicker.vue
  src/components/widgets/camera/CameraMenu.vue
  src/components/widgets/console/ConsoleCard.vue
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/components/widgets/filesystem/FileSystemFilterMenu.vue
  src/components/widgets/filesystem/FileSystemMenu.vue
  src/components/widgets/job-queue/JobQueueContextMenu.vue
  src/components/widgets/status/PauseResumeBtn.vue
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/thermals/TemperaturePresetsMenu.vue
Labels: UI - Change

#1064 fix: mistype in ru locale
  src/locales/ru.yaml
Labels: UI - Translations

#1065 fix: assume untrusted user before config receival
  src/mixins/files.ts
Labels: GH - Bug

#1067 fix: include extra sensor data on temperature_fan
  src/components/widgets/thermals/TemperatureTargets.vue
  src/store/printer/getters.ts
Labels: GH - Bug

#1069 fix: only add parts with defined polygon
  src/workers/parseGcode.ts
Labels: GH - Bug

#1071 feat: adds new Tools menu to Tool card
  src/components/widgets/toolhead/ToolheadCard.vue
  src/globals.ts
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/es.yaml
  src/locales/hu.yaml
  src/locales/ja.yaml
  src/locales/ru.yaml
  src/locales/uk.yaml
  src/locales/zh-CN.yaml
  src/locales/zh-HK.yaml
Labels: FR - Enhancement

#1076 fix: add legacy bed mesh profiles from config
  src/store/mesh/getters.ts
  src/store/mesh/types.ts
  src/store/printer/state.ts
Labels: GH - Bug

#1072 feat(i18n-zh-HK): update Traditional Chinese translations
  src/locales/zh-HK.yaml
Labels: UI - Translations

#1077 feat: adds Go To File dialog
  components.d.ts
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemAddMenu.vue
  src/components/widgets/filesystem/FileSystemBulkActions.vue
  src/components/widgets/filesystem/FileSystemGoToFileDialog.vue
  src/components/widgets/filesystem/FileSystemToolbar.vue
  src/locales/en.yaml
  src/mixins/state.ts
Labels: FR - Enhancement
