Repository fluidd-core/fluidd, pull requests merged in 2023-09, with the labels that each got.

#1162 fix(i18n-DE): Fix typo in german translation
  src/locales/de.yaml
Labels: UI - Translations

#1168 fix: adds more chart colors for sensors
  src/plugins/colorSet.ts
Labels: GH - Bug

#1167 fix: use full Klipper key for thermal data storage
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/components/widgets/thermals/ThermalChart.vue
  src/store/chart_helpers.ts
  src/store/charts/actions.ts
Labels: GH - Bug

#1175 fix: delta printers can only home all
  src/components/widgets/toolhead/ToolheadMoves.vue
Labels: GH - Bug

#1179 Update ru.yaml
  src/locales/ru.yaml
Labels: UI - Translations

#1177 feat: Adds toolhead bars style controls
  components.d.ts
  src/components/settings/ToolheadSettings.vue
  src/components/ui/AppUpDownBtnGroup.vue
  src/components/widgets/toolhead/Toolhead.vue
  src/components/widgets/toolhead/ToolheadControlBars.vue
  src/components/widgets/toolhead/ToolheadControlBarsAxis.vue
  src/components/widgets/toolhead/ToolheadControlBarsStepper.vue
  src/components/widgets/toolhead/ToolheadControlCross.vue
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/printer/getters.ts
Labels: FR - Enhancement, UI - Change

#1182 feat: Added "calibrate" button to BedMeshCard
  src/components/widgets/bedmesh/BedMeshCard.vue
Labels: FR - Enhancement

#1186 feat(spoolman): allow toggling individual sanity check warnings
  src/components/settings/SpoolmanSettings.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#1183 feat(i18n-RU): update Russian translations
  src/locales/ru.yaml
Labels: UI - Translations

#1191 chore: updates to the latest axios dependency
  package-lock.json
  package.json
  src/api/httpClientActions.ts
  src/components/common/AddInstanceDialog.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemDownloadDialog.vue
  src/components/widgets/filesystem/FileSystemUploadDialog.vue
  src/mixins/files.ts
  src/plugins/filters.ts
  src/plugins/httpClient.ts
  src/store/files/actions.ts
  src/store/files/mutations.ts
  src/store/files/state.ts
  src/store/files/types.ts
  tests/unit/setup.ts
Labels: Code - Deps

#1188 feat(i18n-PL): update Polish translations
  src/locales/pl.yaml
Labels: UI - Translations

#1194 fix: ensures .git folders are excluded
  src/globals.ts
  src/store/files/actions.ts
  src/store/files/types.ts
  src/util/get-file-paths.ts
Labels: GH - Bug
