Repository fluidd-core/fluidd, pull requests merged in 2023-08, with the labels that each got.

#1119 feat: spoolman support
  docs/assets/images/spoolman-dashboard-card.png
  docs/assets/images/spoolman-scan-spool.png
  docs/features/spoolman.md
  docs/index.md
  package-lock.json
  package.json
  src/App.vue
  src/api/socketActions.ts
  src/components/layout/AppSettingsNav.vue
  src/components/settings/SpoolmanSettings.vue
  src/components/settings/ToolheadSettings.vue
  src/components/widgets/camera/CameraItem.vue
  src/components/widgets/camera/services/HlsstreamCamera.vue
  src/components/widgets/camera/services/IpstreamCamera.vue
  src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue
  src/components/widgets/camera/services/MjpegstreamerCamera.vue
  src/components/widgets/camera/services/WebrtcCamerastreamerCamera.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/spoolman/QRReader.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/components/widgets/spoolman/SpoolmanCard.vue
  src/components/widgets/status/PrinterStatusCard.vue
  src/components/widgets/toolhead/ToolheadCard.vue
  src/globals.ts
  src/locales/de.yaml
  src/locales/en.yaml
  src/plugins/filters.ts
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/index.ts
  src/store/layout/mutations.ts
  src/store/layout/state.ts
  src/store/socket/actions.ts
  src/store/spoolman/actions.ts
  src/store/spoolman/getters.ts
  src/store/spoolman/index.ts
  src/store/spoolman/mutations.ts
  src/store/spoolman/state.ts
  src/store/spoolman/types.ts
  src/views/Dashboard.vue
  src/views/Settings.vue
Labels: FR - Enhancement

#1130 feat(i18n-PL): update Polish translations
  src/locales/pl.yaml
Labels: UI - Translations

#1134 feat(i18n-HU): Update Hungarian translations
  src/locales/hu.yaml
Labels: UI - Translations

#1139 fix: ignore null on thermal change calculation
  src/components/widgets/thermals/TemperatureTargets.vue
Labels: GH - Bug

#1145 fix: use current origin for relative camera URLs
  src/mixins/camera.ts
Labels: GH - Bug

#1135 feat(i18n-PL): update Polish translations
  src/locales/pl.yaml
Labels: UI - Translations

#1146 feat: add material type column to Spoolman dialog
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
Labels: FR - Enhancement

#1149 feat(spoolman): QR code scanning support
  docs/features/spoolman.md
  src/components/settings/SpoolmanSettings.vue
  src/components/widgets/camera/CameraItem.vue
  src/components/widgets/camera/services/DeviceCamera.vue
  src/components/widgets/spoolman/QRReader.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/cameras/types.ts
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#1159 fix: reset camera on change
  src/mixins/camera.ts
Labels: GH - Bug

#1154 feat(i18n-PL): update Polish translations
  src/locales/pl.yaml
Labels: UI - Translations
