Repository fluidd-core/fluidd, pull requests merged in 2023-01, with the labels that each got.

#988 feat(i18n-JA): update Japanese language
  src/locales/ja.yaml
Labels: UI - Translations

#999 feat: fullscreen Gcode Preview
  src/components/layout/AppNavDrawer.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/router/index.ts
  src/views/GcodePreview.vue
  src/views/Tune.vue
Labels: FR - Enhancement, UI - QoL

#1002 fix: sets maximum notifications lines to 5
  src/components/layout/AppNotificationMenu.vue
Labels: GH - Bug

#1004 style: make upload & print icon consistent
  src/components/layout/AppBar.vue
  src/components/layout/AppUploadAndPrintBtn.vue
Labels: GH - Bug, UI - QoL

#1009 chore: remove "title" and "desc" from all SVGs
  docs/assets/images/fluidd_icon.svg
  docs/assets/images/logo.svg
  public/color_picker.svg
  public/img/icons/safari-pinned-tab.svg
  public/logo_annex.svg
  src/assets/logo.svg
Labels: GH - Bug

#1007 feat: adds support to create ZIP archives
  src/api/socketActions.ts
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/filesystem/FileSystemBulkActions.vue
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/server/getters.ts
  src/store/server/types.ts
  src/store/version/getters.ts
  src/util/number-array-compare.ts
  src/views/Configure.vue
Labels: FR - Enhancement, UI - QoL

#1013 feat: allow sorting text by version or prefix number
  src/components/settings/GeneralSettings.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/locales/en.yaml
  src/plugins/filters.ts
  src/store/config/state.ts
  src/store/config/types.ts
  src/util/__tests__/version-string-compare.spec.ts
  src/util/version-string-compare.ts
Labels: FR - Enhancement

#1015 feat: complete folder upload
  src/components/layout/AppUploadAndPrintBtn.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemDragOverlay.vue
  src/components/widgets/filesystem/FileSystemMenu.vue
  src/globals.ts
  src/locales/en.yaml
  src/mixins/files.ts
  src/util/file-system-entry.ts
Labels: FR - Enhancement

#1006 feat: Add all endpoints in config as printer instances
  src/init.ts
Labels: FR - Enhancement

#1019 feat: show live speed while printing
  src/components/widgets/toolhead/ToolheadPosition.vue
Labels: FR - Enhancement
