Repository fluidd-core/fluidd, pull requests merged in 2023-10, with the labels that each got.

#1197 feat: expands tool change support to commands
  src/components/widgets/toolhead/ToolChangeCommands.vue
  src/components/widgets/toolhead/ToolChangeMacros.vue
  src/components/widgets/toolhead/Toolhead.vue
  src/locales/en.yaml
  src/store/macros/getters.ts
Labels: FR - Enhancement

#1196 feat: adds Moonraker sensor support
  src/api/socketActions.ts
  src/components/widgets/sensors/Sensors.vue
  src/components/widgets/sensors/SensorsCard.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/index.ts
  src/store/layout/state.ts
  src/store/sensors/actions.ts
  src/store/sensors/getters.ts
  src/store/sensors/index.ts
  src/store/sensors/mutations.ts
  src/store/sensors/state.ts
  src/store/sensors/types.ts
  src/store/socket/actions.ts
  src/views/Dashboard.vue
Labels: FR - Enhancement

#1200 refactor: thumbnails code and typings
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/status/ReprintTab.vue
  src/components/widgets/status/StatusTab.vue
  src/mixins/files.ts
  src/store/files/getters.ts
  src/store/files/types.metadata.ts
  src/store/files/types.ts
Labels: FR - Enhancement

#1204 feat: improve drag & drop support
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/job-queue/JobQueue.vue
  src/locales/en.yaml
Labels: FR - Enhancement, Code - Optimizations

#1205 feat: adds moonraker "route_prefix" support
  src/components/common/AddInstanceDialog.vue
  src/plugins/filters.ts
Labels: FR - Enhancement, Code - Optimizations

#1207 fix: adds support for public base path
  index.html
  public/config.json
  server/config.json
  src/components/ui/AppIcon.vue
  src/init.ts
  src/store/config/getters.ts
  src/store/config/state.ts
Labels: GH - Bug, Code - Optimizations

#1199 chore(i18n): translations update from hosted Weblate
  src/locales/de.yaml
  src/locales/pl.yaml
Labels: UI - Translations

#1201 Update HUNgarian Language
  src/locales/hu.yaml
Labels: UI - Translations

#1215 feat: adds Update Manager warnings and anomalies support
  src/components/settings/VersionSettings.vue
Labels: FR - Enhancement

#1213 feat: adds Multiply context menu item to Job Queue
  src/components/widgets/job-queue/JobQueue.vue
  src/components/widgets/job-queue/JobQueueBulkActions.vue
  src/components/widgets/job-queue/JobQueueContextMenu.vue
  src/components/widgets/job-queue/JobQueueMultiplyJobDialog.vue
  src/locales/en.yaml
Labels: FR - Enhancement

#1217 feat: ignore pending config changes in custom sections
  src/components/layout/AppBar.vue
  src/components/settings/FileEditorSettings.vue
  src/components/settings/GeneralSettings.vue
  src/locales/af.yaml
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/hu.yaml
  src/locales/pl.yaml
  src/locales/ru.yaml
  src/locales/zh-CN.yaml
  src/store/config/state.ts
  src/store/config/types.ts
  src/util/is-key-of.ts
Labels: FR - Enhancement

#1222 fix: mixed ISO / non-ISO date & time formats
  src/components/settings/GeneralSettings.vue
  src/globals.ts
  src/plugins/filters.ts
Labels: GH - Bug
