Repository fluidd-core/fluidd, pull requests merged in 2023-02, with the labels that each got.

#1022 feat: Pressure Advance per extruder stepper
  src/components/widgets/toolhead/ExtruderStats.vue
  src/components/widgets/toolhead/PressureAdvanceAdjust.vue
  src/components/widgets/toolhead/Toolhead.vue
  src/store/printer/getters.ts
  src/store/printer/types.ts
Labels: GH - Bug, FR - Enhancement

#1024 fix: encode all request paths
  src/App.vue
  src/api/httpClientActions.ts
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/timelapse/TimelapseStatusCard.vue
  src/mixins/files.ts
Labels: GH - Bug

#1025 feat: Add support for gcode viewing on plotter-style devices
  src/store/gcodePreview/getters.ts
Labels: GH - Bug

#1026 feat(i18n-zh): updates Chinese translations
  src/locales/zh-CN.yaml
  src/locales/zh-HK.yaml
Labels: UI - Translations

#1028 feat: setting to disable automatic gcode loading on mobile
  src/components/settings/GcodePreviewSettings.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#1031 feat: try parsing layer info directly from g-code
  src/components/settings/GcodePreviewSettings.vue
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/gcodePreview/actions.ts
  src/store/gcodePreview/getters.ts
  src/store/gcodePreview/mutations.ts
  src/store/gcodePreview/state.ts
  src/store/gcodePreview/types.ts
  src/workers/parseGcode.ts
  src/workers/parseGcode.worker.ts
Labels: FR - Enhancement

#1033 feat: make file download dialog component independent from parent
  src/App.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemDownloadDialog.vue
  src/mixins/files.ts
  src/store/files/actions.ts
  src/store/files/mutations.ts
  src/store/files/state.ts
  src/store/files/types.ts
Labels: Code - Optimizations

#1034 feat: extruder selection for each extruder stepper
  src/components/widgets/toolhead/ExtruderStepperSync.vue
  src/components/widgets/toolhead/ExtruderSteppers.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/printer/getters.ts
  src/store/printer/types.ts
Labels: FR - Enhancement

#1035 feat(timelapse): add new park positions
  src/components/settings/timelapse/subsettings/CustomParkPositionSettings.vue
  src/components/settings/timelapse/subsettings/ToolheadParkingSettings.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/timelapse/types.ts
Labels: FR - Enhancement

#1039 feat: adds support for extruder stepper enable
  src/components/widgets/toolhead/ExtruderStepperSync.vue
  src/components/widgets/toolhead/ExtruderSteppers.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/printer/getters.ts
  src/store/printer/types.ts
Labels: FR - Enhancement

#1042 refactor: input control improvements
  components.d.ts
  src/components/layout/AppNavDrawer.vue
  src/components/layout/AppNotificationMenu.vue
  src/components/ui/AppMacroBtn.vue
  src/components/ui/AppNamedSelect.vue
  src/components/ui/AppNamedSlider.vue
  src/components/ui/AppNamedSwitch.vue
  src/components/ui/AppTable.vue
  src/components/ui/AppTextField.vue
  src/components/widgets/camera/CameraCard.vue
  src/components/widgets/console/ConsoleCard.vue
  src/components/widgets/diagnostics/DiagnosticsCard.vue
  src/components/widgets/diagnostics/config/MetricsConfigStep.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/filesystem/FileSystemToolbar.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/jobs/JobsCard.vue
  src/components/widgets/limits/PrinterLimits.vue
  src/components/widgets/limits/PrinterLimitsCard.vue
  src/components/widgets/macros/MacrosCard.vue
  src/components/widgets/outputs/OutputFan.vue
  src/components/widgets/outputs/OutputPin.vue
  src/components/widgets/outputs/OutputsCard.vue
  src/components/widgets/retract/Retract.vue
  src/components/widgets/retract/RetractCard.vue
  src/components/widgets/status/PrinterStatusCard.vue
  src/components/widgets/thermals/InputTemperature.vue
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/components/widgets/timelapse/TimelapseRenderSettingsDialog.vue
  src/components/widgets/timelapse/TimelapseSettingsCard.vue
  src/components/widgets/timelapse/TimelapseStatusCard.vue
  src/components/widgets/toolhead/ExtruderStepperSync.vue
  src/components/widgets/toolhead/PressureAdvanceAdjust.vue
  src/components/widgets/toolhead/SpeedAndFlowAdjust.vue
  src/components/widgets/toolhead/ToolheadCard.vue
  src/store/printer/getters.ts
  src/views/Configure.vue
  src/views/FullscreenCamera.vue
  src/views/Jobs.vue
  src/views/Timelapse.vue
Labels: FR - Enhancement, Code - Optimizations

#1041 feat: allow ordering of gcode macros
  src/components/settings/macros/MacroSettings.vue
  src/store/macros/actions.ts
  src/store/macros/getters.ts
  src/store/macros/types.ts
Labels: FR - Enhancement

#1043 Hungarian language update
  src/locales/hu.yaml
Labels: UI - Translations

#1045 chore: refactor isMobile to use mixin
  src/App.vue
  src/components/layout/AppBar.vue
  src/components/layout/AppNavDrawer.vue
  src/components/layout/AppNotificationMenu.vue
  src/components/ui/AppChart.vue
  src/components/ui/AppNamedSlider.vue
  src/components/ui/AppNavItem.vue
  src/components/widgets/bedmesh/BedMeshCard.vue
  src/components/widgets/bedmesh/BedMeshChart.vue
  src/components/widgets/diagnostics/DiagnosticsCard.vue
  src/components/widgets/filesystem/FileEditor.vue
  src/components/widgets/filesystem/FileEditorDialog.vue
  src/components/widgets/gcode-preview/GcodePreview.vue
  src/components/widgets/gcode-preview/GcodePreviewButton.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/limits/PrinterLimits.vue
  src/components/widgets/outputs/OutputFan.vue
  src/components/widgets/outputs/OutputLed.vue
  src/components/widgets/outputs/OutputPin.vue
  src/components/widgets/retract/Retract.vue
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/thermals/ThermalChart.vue
  src/components/widgets/toolhead/PressureAdvanceAdjust.vue
  src/components/widgets/toolhead/SpeedAndFlowAdjust.vue
  src/mixins/browser.ts
  src/util/is-mobile.ts
Labels: Code - Optimizations

#1046 feat: show parts on Gcode Previewer
  package-lock.json
  package.json
  src/components/ui/AppNamedSlider.vue
  src/components/widgets/exclude-objects/ExcludeObjects.vue
  src/components/widgets/gcode-preview/GcodePreview.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/gcodePreview/actions.ts
  src/store/gcodePreview/getters.ts
  src/store/gcodePreview/mutations.ts
  src/store/gcodePreview/state.ts
  src/store/gcodePreview/types.ts
  src/store/socket/actions.ts
  src/workers/parseGcode.ts
  src/workers/parseGcode.worker.ts
Labels: FR - Enhancement

#1047 feat: adds HLS camera stream support
  package-lock.json
  package.json
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/widgets/camera/CameraItem.vue
  src/locales/en.yaml
  src/store/cameras/actions.ts
  src/store/cameras/mutations.ts
  src/store/cameras/types.ts
  vite.config.ts
Labels: FR - Enhancement

#1048 feat(i18n-UK): update Ukrainian translations
  src/locales/uk.yaml
Labels: UI - Translations
