Repository fluidd-core/fluidd, pull requests merged in 2023-05, with the labels that each got.

#1093 refactor: file system improvements
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/filesystem/FileSystemContextMenu.vue
  src/components/widgets/filesystem/FileSystemFilterMenu.vue
  src/components/widgets/filesystem/FileSystemGoToFileDialog.vue
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/status/ReprintTab.vue
  src/components/widgets/status/StatusTab.vue
  src/mixins/files.ts
  src/store/config/getters.ts
  src/store/config/types.ts
  src/store/files/actions.ts
  src/store/files/getters.ts
  src/store/files/mutations.ts
  src/store/files/state.ts
  src/store/files/types.ts
  src/store/history/actions.ts
  src/util/get-file-paths.ts
  src/util/merge-file-update.ts
Labels: Code - Optimizations

#1096 fix: allow ignoring min_extrude_temp for load/unload filament macros
  src/components/widgets/toolhead/ToolheadCard.vue
Labels: FR - Enhancement

#1097 i18n: improves delete confirmation message
  src/components/widgets/filesystem/FileSystem.vue
  src/locales/ar.yaml
  src/locales/cs.yaml
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/es.yaml
  src/locales/fr.yaml
  src/locales/hu.yaml
  src/locales/it.yaml
  src/locales/ja.yaml
  src/locales/ko.yaml
  src/locales/nl.yaml
  src/locales/pt.yaml
  src/locales/sl.yaml
  src/locales/uk.yaml
  src/locales/zh-CN.yaml
  src/locales/zh-HK.yaml
Labels: UI - Translations

#1098 feat(i18n-JA): update Japanese language
  src/locales/ja.yaml
Labels: UI - Translations

#1099 feat: save and restore editor view state
  src/components/settings/FileEditorSettings.vue
  src/components/widgets/filesystem/FileEditor.vue
  src/components/widgets/filesystem/FileEditorDialog.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
  src/util/md5-as-base64.ts
Labels: FR - Enhancement

#1101 fix: more selective keyboard events for history navigation
  src/components/widgets/console/ConsoleCommand.vue
Labels: GH - Bug
