Repository fluidd-core/fluidd, pull requests merged in 2023-04, with the labels that each got.

#1079 feat: adds load/unload filament support
  src/components/widgets/toolhead/ToolheadCard.vue
Labels: FR - Enhancement

#1083 feat: filter hidden folders as well as files
  src/components/widgets/filesystem/FileSystem.vue
  src/locales/en.yaml
Labels: GH - Bug, FR - Enhancement

#1086 fix: allow applying z-offset to endstop or probe
  src/components/widgets/toolhead/ZHeightAdjust.vue
  src/globals.ts
Labels: GH - Bug

#1088 feat(i18n-SI): adds Slovenian translations
  src/globals.ts
  src/locales/sl.yaml
Labels: UI - Translations

#1094 fix: adds missing File Browser button tooltips
  components.d.ts
  src/components/ui/AppColumnPicker.vue
  src/components/ui/AppThumbnailSize.vue
  src/components/widgets/filesystem/FileSystemToolbar.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/files/getters.ts
Labels: GH - Bug
