Repository fluidd-core/fluidd, pull requests merged in 2024-12, with the labels that each got.

#1543 fix: group and wrap tool change commands
  src/components/widgets/toolhead/ToolChangeCommands.vue
Labels: GH - Bug

#1548 feat: adds Kalico config support
  src/globals.ts
Labels: FR - Enhancement

#1546 feat: adds Adjust Dashboard Layout sidebar button
  src/components/common/SystemLayout.vue
  src/components/layout/AppNavDrawer.vue
  src/components/ui/AppTextFieldWithCopy.vue
  src/components/widgets/filesystem/FileSystemUploadDialog.vue
  src/router/index.ts
Labels: FR - Enhancement

#1547 chore(i18n): translations update from hosted Weblate
  src/locales/hu.yaml
Labels: UI - Translations

#1551 fix: Moonraker canbus uuid parameter
  src/components/common/PeripheralsDialog.vue
  src/store/server/mutations.ts
Labels: GH - Bug

#1558 fix(Heaters): no context menu on left click
  src/components/widgets/thermals/TemperatureTargets.vue
Labels: GH - Bug

#1560 fix: clipboard copy on non-secure context
  src/components/ui/AppTextFieldWithCopy.vue
  src/scss/misc.scss
  src/util/clipboard-copy.ts
Labels: GH - Bug

#1559 feat(Heaters): adds MPC_CALIBRATE support
  src/components/widgets/thermals/HeaterContextMenu.vue
  src/components/widgets/thermals/HeaterMpcCalibrateDialog.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/locales/en.yaml
  src/store/printer/getters.ts
Labels: FR - Enhancement

#1563 fix: lower case variable name for SAVE_VARIABLE
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
Labels: GH - Bug
