Repository fluidd-core/fluidd, pull requests merged in 2024-01, with the labels that each got.

#1299 fix: default to user language as Intl format
  src/components/settings/GeneralSettings.vue
  src/plugins/filters.ts
Labels: GH - Bug

#1252 feat: improves status panel layout
  src/components/widgets/status/StatusTab.vue
Labels: FR - Enhancement, UI - QoL

#1303 fix: file browser filters list
  src/components/widgets/filesystem/FileSystemFilterMenu.vue
Labels: GH - Bug

#1305 feat(spoolman): remember spool selection dialog sort key/order
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#1307 fix: correctly show the active root
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemToolbar.vue
Labels: GH - Bug

#1310 feat(GcodePreview): add option to hide part bounding box when printing a single part
  src/components/settings/GcodePreviewSettings.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/gcodePreview/actions.ts
Labels: FR - Enhancement

#1311 docs(thumbnails): prusa slicer syntax update
  docs/features/thumbnails.md
Labels: Docs - Enhancement

#1319 i18n: adds translation keys for System Utilization labels
  src/components/widgets/system/KlipperLoadChart.vue
  src/components/widgets/system/McuLoadChart.vue
  src/components/widgets/system/MoonrakerLoadChart.vue
  src/components/widgets/system/SystemLoadChart.vue
  src/components/widgets/system/SystemMemoryChart.vue
  src/locales/en.yaml
Labels: UI - Translations

#1316 feat(spoolman): handle v2 responses, improve connection error handling
  src/api/socketActions.ts
  src/components/layout/AppSettingsNav.vue
  src/components/settings/ToolheadSettings.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/spoolman/SpoolmanCard.vue
  src/components/widgets/status/PrinterStatusCard.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/store/socket/actions.ts
  src/store/spoolman/actions.ts
  src/store/spoolman/getters.ts
  src/store/spoolman/mutations.ts
  src/store/spoolman/state.ts
  src/store/spoolman/types.ts
  src/views/Dashboard.vue
  src/views/Settings.vue
Labels: FR - Enhancement, Upstream - Moonraker

#1321 fix: ignore Authorization on login or token refresh
  src/store/auth/actions.ts
Labels: GH - Bug

#1296 chore(i18n): translations update from hosted Weblate
  src/locales/de.yaml
  src/locales/nl.yaml
  src/locales/pl.yaml
  src/locales/pt.yaml
  src/locales/ru.yaml
Labels: UI - Translations

#1291 feat(i18n-HU): Update Hungarian translations
  src/locales/hu.yaml
Labels: UI - Translations

#1322 docs(octoeverywhere): updating the docs with new project updates
  docs/configuration/octoeverywhere_free_remote_access.md
Labels: Docs - Enhancement

#1326 chore: updates GitHub workflows
  .github/workflows/build.yml
Labels: Code - Infrastructure

#1327 refactor(cameras): use cached url object for adaptive MJPEG sources
  src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue
Labels: Code - Optimizations

#1330 fix: file path on upload
  src/mixins/files.ts
  src/util/file-system-entry.ts
Labels: GH - Bug

#1332 feat(FileSystem): add crowsnest backup file filter
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemFilterMenu.vue
  src/locales/en.yaml
  src/store/files/getters.ts
  src/store/files/types.ts
Labels: FR - Enhancement

#1328 feat: improve support for adaptive bedmeshes
  src/components/widgets/bedmesh/BedMeshControls.vue
  src/components/widgets/bedmesh/SaveMeshDialog.vue
  src/store/mesh/getters.ts
  src/store/mesh/types.ts
Labels: FR - Enhancement
