Repository fluidd-core/fluidd, pull requests merged in 2024-03, with the labels that each got.

#1378 feat: add finish time selection from slicer or file
  src/components/settings/GeneralSettings.vue
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/printer/getters.ts
Labels: FR - Enhancement

#1380 fix(FilePreviewDialog): make `path` property optional
  src/components/widgets/filesystem/FilePreviewDialog.vue
Labels: GH - Bug

#1382 fix: disable Check Updates button if printer printing
  src/components/settings/VersionSettings.vue
Labels: GH - Bug

#1387 fix(spoolman): missing filament material in selection dialog
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
Labels: GH - Bug

#1386 refactor: Moonraker Webcam API
  src/api/httpClientActions.ts
  src/api/socketActions.ts
  src/components/settings/SpoolmanSettings.vue
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/settings/cameras/CameraSettings.vue
  src/components/settings/timelapse/TimelapseSettings.vue
  src/components/widgets/camera/CameraCard.vue
  src/components/widgets/camera/CameraDialog.vue
  src/components/widgets/camera/CameraItem.vue
  src/components/widgets/camera/CameraMenu.vue
  src/components/widgets/camera/services/HlsstreamCamera.vue
  src/components/widgets/camera/services/IframeCamera.vue
  src/components/widgets/camera/services/IpstreamCamera.vue
  src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue
  src/components/widgets/camera/services/MjpegstreamerCamera.vue
  src/components/widgets/camera/services/WebrtcCamerastreamerCamera.vue
  src/components/widgets/camera/services/WebrtcGo2RtcCamera.vue
  src/components/widgets/spoolman/QRReader.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/components/widgets/timelapse/TimelapseStatusCard.vue
  src/globals.ts
  src/init.ts
  src/locales/en.yaml
  src/mixins/camera.ts
  src/store/cameras/actions.ts
  src/store/cameras/getters.ts
  src/store/cameras/index.ts
  src/store/cameras/mutations.ts
  src/store/cameras/state.ts
  src/store/cameras/types.ts
  src/store/index.ts
  src/store/server/actions.ts
  src/store/server/mutations.ts
  src/store/server/types.ts
  src/store/types.ts
  src/store/webcams/actions.ts
  src/store/webcams/getters.ts
  src/store/webcams/mutations.ts
  src/store/webcams/state.ts
  src/store/webcams/types.ts
  src/views/Dashboard.vue
  src/views/FullscreenCamera.vue
Labels: FR - Enhancement

#1388 fix: Armbian distribution information
  src/components/widgets/system/SystemOverviewCard.vue
Labels: GH - Bug

#1383 feat: adds support for machine peripherals
  components.d.ts
  src/api/socketActions.ts
  src/components/common/PeripheralsDialog.vue
  src/components/ui/AppTextFieldWithCopy.vue
  src/components/widgets/filesystem/FileEditorDialog.vue
  src/components/widgets/system/SystemOverviewCard.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/printer/actions.ts
  src/store/server/actions.ts
  src/store/server/mutations.ts
  src/store/server/state.ts
  src/store/server/types.ts
Labels: FR - Enhancement

#1389 feat: layout improvements for small screen
  src/components/common/AddInstanceDialog.vue
  src/components/common/PeripheralsDialog.vue
  src/components/common/ScrewsTiltAdjustDialog.vue
  src/components/settings/auth/UserConfigDialog.vue
  src/components/settings/auth/UserPasswordDialog.vue
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/settings/console/ConsoleFilterDialog.vue
  src/components/settings/macros/MacroSettingsDialog.vue
  src/components/settings/presets/PresetDialog.vue
  src/components/ui/AppDialog.vue
  src/components/ui/AppSetting.vue
  src/components/widgets/diagnostics/DiagnosticsCardConfigDialog.vue
  src/components/widgets/filesystem/FileSystemToolbar.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/components/widgets/status/PauseAtLayerDialog.vue
  src/components/widgets/system/McuInformationDialog.vue
  src/components/widgets/timelapse/TimelapseRenderSettingsDialog.vue
Labels: UI - Change, UI - Mobile

#1370 feat(i18n-JA): update Japanese language
  src/locales/ja.yaml
Labels: UI - Translations

#1367 feat(i18n-HU): Update Hungarian translations
  src/locales/hu.yaml
Labels: UI - Translations

#1391 feat: allow showing Runout Sensors on Dashboard
  src/components/widgets/runout-sensors/RunoutSensorsCard.vue
  src/store/layout/state.ts
  src/views/Dashboard.vue
  src/views/Tune.vue
Labels: FR - Enhancement

#1393 feat(i18n-TR): Updates Turkish translations
  src/globals.ts
  src/locales/tr.yaml
Labels: UI - Translations

#1397 fix: use Klipper can_extrude by default
  src/mixins/toolhead.ts
Labels: GH - Bug

#1396 fix: removes "Filter printed" menu item description
  src/components/widgets/filesystem/FileSystemFilterMenu.vue
  src/locales/af.yaml
  src/locales/ar.yaml
  src/locales/cs.yaml
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/es.yaml
  src/locales/fr.yaml
  src/locales/hu.yaml
  src/locales/it.yaml
  src/locales/ja.yaml
  src/locales/ko.yaml
  src/locales/nl.yaml
  src/locales/pl.yaml
  src/locales/pt.yaml
  src/locales/ru.yaml
  src/locales/sl.yaml
  src/locales/tr.yaml
  src/locales/uk.yaml
  src/locales/zh-CN.yaml
  src/locales/zh-HK.yaml
Labels: GH - Bug

#1114 feat: basic Nevermore Controller support
  src/store/printer/getters.ts
Labels: FR - Enhancement

#1399 fix: progress not shown a number
  src/store/printer/getters.ts
Labels: GH - Bug
