Repository fluidd-core/fluidd, pull requests merged in 2024-04, with the labels that each got.

#1406 feat(FileSystem): remember last sort order
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/store/config/actions.ts
  src/store/config/mutations.ts
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#1404 feat: adds keyboard shortcuts
  components.d.ts
  src/App.vue
  src/components/common/KeyboardShortcutsDialog.vue
  src/components/layout/AppBar.vue
  src/components/layout/AppNavDrawer.vue
  src/components/settings/GeneralSettings.vue
  src/components/ui/AppNavItem.vue
  src/components/widgets/bedmesh/BedMeshControls.vue
  src/components/widgets/filesystem/FileEditor.vue
  src/components/widgets/filesystem/FileEditorDialog.vue
  src/components/widgets/status/StatusControls.vue
  src/components/widgets/toolhead/ToolheadControlBars.vue
  src/components/widgets/toolhead/ToolheadControlCircle.vue
  src/components/widgets/toolhead/ToolheadControlCross.vue
  src/globals.ts
  src/locales/en.yaml
  src/mixins/state.ts
  src/scss/misc.scss
  src/store/config/state.ts
  src/store/config/types.ts
  src/util/event-helpers.ts
Labels: FR - Enhancement

#1409 feat: adds WebRTC (MediaMTX) support
  docs/features/cameras.md
  src/components/settings/cameras/CameraConfigDialog.vue
  src/components/widgets/camera/services/WebrtcMediamtxCamera.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/hu.yaml
  src/locales/ja.yaml
  src/locales/ko.yaml
  src/locales/pl.yaml
  src/locales/ru.yaml
  src/locales/sl.yaml
  src/locales/tr.yaml
  src/store/webcams/types.ts
Labels: FR - Enhancement

#1411 fix(spoolman): improve sanity check logic
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/store/printer/getters.ts
Labels: GH - Bug

#1414 feat: print progress estimation improvements
  src/components/settings/GeneralSettings.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/tr.yaml
  src/store/config/types.ts
  src/store/printer/getters.ts
Labels: FR - Enhancement

#1416 fix(gcodepreview): ignore moves without coordinates
  src/components/widgets/gcode-preview/GcodePreview.vue
  src/workers/parseGcode.ts
Labels: GH - Bug

#1418 feat: show all fan and pin values as percentages
  src/components/ui/AppNamedSwitch.vue
  src/components/widgets/outputs/OutputFan.vue
  src/components/widgets/outputs/OutputPin.vue
  src/store/printer/getters.ts
  src/store/printer/types.ts
Labels: FR - Enhancement, UI - Change

#1413 feat(i18n-RU): update Russian translations
  src/locales/ru.yaml
Labels: UI - Translations

#1425 feat: use correct stepper temperature label
  src/locales/en.yaml
  src/store/printer/getters.ts
Labels: FR - Enhancement

#1427 feat: backup and restore settings
  src/components/layout/AppSettingsNav.vue
  src/components/settings/GeneralSettings.vue
  src/locales/en.yaml
  src/util/file-system-entry.ts
  src/util/fluidd-content.ts
Labels: FR - Enhancement
