Repository fluidd-core/fluidd, pull requests merged in 2024-08, with the labels that each got.

#1469 feat: improve alignment of runout sensor switch and icon
  components.d.ts
  src/components/widgets/runout-sensors/RunoutSensorsCard.vue
  src/store/printer/getters.ts
Labels: UI - QoL

#1477 fix: Check for Meta key on keyboard shortcuts
  src/util/event-helpers.ts
Labels: GH - Bug

#1479 fix: Dynamic loading of camera components
  src/components/widgets/camera/CameraItem.vue
Labels: GH - Bug

#1482 feat(FileSystem): Filter KlipperScreen rolled logs
  src/components/widgets/filesystem/FileSystem.vue
Labels: FR - Enhancement

#1483 fix: don't use separator for gcode macros
  src/components/widgets/macros/MacroBtn.vue
Labels: GH - Bug

#1484 fix: null check cards on layout init
  src/store/layout/mutations.ts
Labels: GH - Bug

#1485 feat: hides macro parameters starting with "_"
  src/util/__tests__/gcode-macro-params.spec.ts
  src/util/gcode-macro-params.ts
Labels: FR - Enhancement
