Repository fluidd-core/fluidd, pull requests merged in 2024-10, with the labels that each got.

#1500 fix: disable "Update All" button when an invalid repo is detected
  src/components/settings/VersionSettings.vue
Labels: GH - Bug

#1505 feat: increase Z precision to 3 decimals
  src/components/ui/AppNamedSlider.vue
  src/components/ui/AppTextField.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/components/widgets/toolhead/ToolheadPosition.vue
Labels: FR - Enhancement, UI - Change

#1507 feat(FileSystem): allow filtering Moonraker temp upload files
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemFilterMenu.vue
  src/locales/en.yaml
  src/store/files/getters.ts
  src/store/files/types.ts
Labels: FR - Enhancement

#1509 style(Console): single auto-complete console entry
  src/components/widgets/console/ConsoleCommand.vue
Labels: FR - Enhancement

#1512 feat: adds status column to job files list
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/history/JobHistoryItemStatus.vue
  src/store/config/state.ts
  src/store/files/types.metadata.ts
  src/store/files/types.ts
Labels: FR - Enhancement

#1513 feat(GcodePreview): save & restore viewer state
  src/components/widgets/gcode-preview/GcodePreview.vue
  src/components/widgets/gcode-preview/GcodePreviewButton.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/gcodePreview/actions.ts
  src/store/gcodePreview/getters.ts
  src/store/gcodePreview/mutations.ts
  src/store/gcodePreview/state.ts
  src/store/gcodePreview/types.ts
Labels: FR - Enhancement

#1514 fix(Charts): allow resetting chart store only
  src/components/widgets/thermals/TemperatureTargets.vue
  src/mixins/services.ts
  src/store/charts/actions.ts
  src/store/charts/mutations.ts
  src/store/index.ts
  src/store/socket/actions.ts
Labels: GH - Bug

#1517 fix: uid check on upload/download state changes
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemUploadDialog.vue
  src/mixins/files.ts
  src/store/files/mutations.ts
  src/store/files/types.ts
Labels: GH - Bug
