Repository fluidd-core/fluidd, pull requests merged in 2024-02, with the labels that each got.

#1340 fix(thermals): size columns dynamically, disallow line breaks
  src/components/widgets/thermals/TemperatureTargets.vue
Labels: GH - Bug, UI - QoL

#1339 feat: improve confirmation messages
  src/components/settings/auth/AuthSettings.vue
  src/components/widgets/bedmesh/BedMeshControls.vue
  src/components/widgets/status/StatusControls.vue
  src/locales/en.yaml
  src/mixins/state.ts
Labels: FR - Enhancement

#1342 fix: console warning when multiple update sources have warnings
  src/components/settings/VersionSettings.vue
Labels: GH - Bug

#1338 feat(spoolman): allow selecting table columns in spool selection dialog
  src/components/ui/AppDialog.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/store/config/state.ts
Labels: FR - Enhancement

#1324 feat(spoolman): multi-tool support
  docs/assets/images/spoolman-multitool.png
  docs/features/spoolman.md
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/components/widgets/spoolman/SpoolmanCard.vue
  src/components/widgets/toolhead/ToolChangeCommands.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/scss/misc.scss
  src/store/spoolman/actions.ts
  src/store/spoolman/getters.ts
  src/store/spoolman/state.ts
  src/store/spoolman/types.ts
Labels: FR - Enhancement

#1329 feat(i18n-SL): Update Slovenian translations
  src/locales/sl.yaml
Labels: UI - Translations

#1345 fix: round OutputPin value
  src/components/widgets/outputs/OutputPin.vue
Labels: GH - Bug

#1348 feat: adds link to components in software updates
  src/components/settings/VersionSettings.vue
Labels: FR - Enhancement

#1341 chore(i18n): translations update from hosted Weblate
  src/locales/de.yaml
  src/locales/hu.yaml
  src/locales/pt.yaml
  src/locales/ru.yaml
Labels: UI - Translations

#1354 fix(spoolman): dialog title
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
Labels: GH - Bug

#1355 fix: don't override `gcode_macro` variables with stale values
  src/store/macros/getters.ts
Labels: GH - Bug

#1356 fix: remove redundant data from stored macros
  src/store/macros/getters.ts
  src/store/macros/mutations.ts
Labels: Code - Optimizations

#1358 feat: adds MCU last stats
  src/components/widgets/system/McuCard.vue
  src/components/widgets/system/McuConstantsDialog.vue
  src/components/widgets/system/McuInformationDialog.vue
  src/locales/en.yaml
  src/store/printer/types.ts
Labels: FR - Enhancement

#1360 style: use Roboto font family in charts
  src/components/widgets/bedmesh/BedMeshChart.vue
  src/components/widgets/diagnostics/DiagnosticsCard.vue
  src/components/widgets/thermals/ThermalChart.vue
  src/store/charts/getters.ts
Labels: GH - Bug, UI - QoL

#1365 feat: adds probe accuracy support
  src/components/widgets/toolhead/ToolheadCard.vue
  src/globals.ts
Labels: FR - Enhancement

#1366 refactor: uses vue2-touch-events for tap
  package-lock.json
  package.json
  src/components/widgets/exclude-objects/ExcludeObjects.vue
  src/main.ts
Labels: GH - Bug

#1353 chore(i18n): translations update from hosted Weblate
  src/locales/nl.yaml
Labels: UI - Translations

#1371 fix(style): text color on bed mesh chart
  src/components/widgets/bedmesh/BedMeshChart.vue
Labels: GH - Bug

#1376 feat: view rendered Markdown files
  package-lock.json
  package.json
  src/components/widgets/filesystem/FilePreviewDialog.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/globals.ts
  src/store/config/state.ts
  src/store/files/getters.ts
Labels: FR - Enhancement

#1375 fix: make color picker use v-model and propsync
  src/components/settings/ThemeSettings.vue
  src/components/settings/macros/MacroSettingsDialog.vue
  src/components/ui/AppColorPicker.vue
  src/components/ui/AppIroColorPicker.vue
  src/components/widgets/diagnostics/config/MetricsConfigStep.vue
  src/components/widgets/outputs/OutputLed.vue
  src/store/diagnostics/types.ts
  src/store/layout/actions.ts
  src/store/layout/mutations.ts
  src/store/layout/state.ts
Labels: GH - Bug

#1374 feat: allow percentage-based inputs in color picker
  src/components/ui/AppColorPicker.vue
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement
