Repository fluidd-core/fluidd, pull requests merged in 2024-11, with the labels that each got.

#1523 chore: updates to eslint v9
  .eslintrc.cjs
  .husky/pre-commit
  eslint.config.mjs
  package-lock.json
  package.json
  src/components/common/RegisterServiceWorker.vue
  src/plugins/filters.ts
  src/plugins/socketClient.ts
  src/store/socket/actions.ts
  src/views/Login.vue
  src/workers/parseGcode.ts
  tools/convertTheme.mjs
Labels: Code - Infrastructure

#1522 fix(ThermalChart): consistent chart color on single device
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/components/widgets/thermals/ThermalChart.vue
  src/store/chart_helpers.ts
  src/store/charts/actions.ts
Labels: GH - Bug

#1524 feat: adds setting for files and folders drag & drop
  src/components/settings/FileBrowserSettings.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#1528 feat: adds config file #region folding support
  src/components/widgets/filesystem/setupMonaco.ts
Labels: FR - Enhancement

#1533 fix: toolhead position controls enabled on pause
  src/components/widgets/toolhead/ToolheadPosition.vue
Labels: GH - Bug

#1472 feat: Mellow theme
  public/config.json
  public/logo_mellow.svg
  server/config.json
Labels: FR - Enhancement

#1535 fix: Job History search
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/stats/PrinterStatsCard.vue
  src/components/widgets/system/DiskUsageCard.vue
Labels: GH - Bug

#1534 feat: Beacon support
  src/components/widgets/beacon/BeaconCard.vue
  src/components/widgets/beacon/SaveModelDialog.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/layout/state.ts
  src/store/printer/getters.ts
  src/store/printer/types.ts
  src/views/Dashboard.vue
  src/views/Tune.vue
Labels: FR - Enhancement

#1539 feat: column reordering
  components.d.ts
  src/components/ui/AppColumnPicker.vue
  src/components/ui/AppDataTableRow.vue
  src/components/widgets/filesystem/FileRowItem.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/job-queue/JobQueue.vue
  src/components/widgets/job-queue/JobQueueBrowser.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/store/config/actions.ts
  src/store/config/getters.ts
  src/store/config/mutations.ts
  src/store/config/state.ts
  src/types/tableheaders.ts
Labels: FR - Enhancement, UI - QoL, UI - Change

#1530 feat: adds _CLIENT_LINEAR_MOVE macro support
  src/components/widgets/toolhead/ToolheadControlBarsAxis.vue
  src/components/widgets/toolhead/ToolheadControlCircle.vue
  src/components/widgets/toolhead/ToolheadControlCross.vue
  src/components/widgets/toolhead/ToolheadPosition.vue
  src/mixins/state.ts
  src/store/macros/getters.ts
Labels: FR - Enhancement

#1542 feat: allow user selection of device camera
  src/components/widgets/camera/CameraItem.vue
  src/components/widgets/camera/services/DeviceCamera.vue
  src/components/widgets/camera/services/IframeCamera.vue
  src/components/widgets/camera/services/IpstreamCamera.vue
  src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue
  src/components/widgets/camera/services/MjpegstreamerCamera.vue
  src/components/widgets/camera/services/WebrtcCamerastreamerCamera.vue
  src/components/widgets/camera/services/WebrtcGo2RtcCamera.vue
  src/locales/en.yaml
  src/mixins/camera.ts
Labels: FR - Enhancement
