Repository fluidd-core/fluidd, pull requests merged in 2025-03, with the labels that each got.

#1617 feat: new Moonraker metadata support
  components.d.ts
  src/components/ui/AppChipColor.vue
  src/components/ui/AppDataTableCellColors.vue
  src/components/ui/AppDataTableCellTemps.vue
  src/components/ui/AppDataTableRow.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/locales/en.yaml
  src/store/files/getters.ts
  src/store/files/types.metadata.ts
  src/store/files/types.ts
  src/store/history/getters.ts
  src/store/history/mutations.ts
  src/store/history/types.ts
  src/util/string-formatters.ts
Labels: FR - Enhancement

#1621 fix(Cameras): always emit frame event
  src/components/widgets/camera/CameraItem.vue
  src/components/widgets/camera/services/IpstreamCamera.vue
  src/components/widgets/camera/services/MjpegstreamerAdaptiveCamera.vue
  src/mixins/camera.ts
Labels: GH - Bug

#1623 fix(FileSystem): metadata types on getFile
  src/store/files/getters.ts
Labels: GH - Bug

#1627 fix(AppBtnToggle): specify v-model property
  src/components/ui/AppBtnToggle.vue
Labels: GH - Bug

#1631 fix(Thermals): show extra sensor data
  src/store/printer/getters.ts
Labels: GH - Bug

#1634 fix(Spoolman): add version check
  src/api/socketActions.ts
  src/store/spoolman/actions.ts
  src/store/spoolman/mutations.ts
  src/store/spoolman/state.ts
  src/store/spoolman/types.ts
Labels: GH - Bug

#1637 feat: show job queue totals
  src/components/ui/AppDragIcon.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/job-queue/JobQueue.vue
  src/components/widgets/job-queue/JobQueueBrowser.vue
  src/components/widgets/job-queue/JobQueueCard.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/locales/en.yaml
  src/store/files/getters.ts
  src/store/files/mutations.ts
  src/store/files/state.ts
  src/store/files/types.ts
  src/store/helpers.ts
  src/store/history/actions.ts
  src/store/jobQueue/actions.ts
  src/store/jobQueue/getters.ts
  src/store/jobQueue/mutations.ts
  src/store/jobQueue/state.ts
  src/store/jobQueue/types.ts
  src/views/Jobs.vue
Labels: FR - Enhancement

#1638 feat(Spoolman): adds new metadata
  src/components/settings/GeneralSettings.vue
  src/components/settings/SpoolmanSettings.vue
  src/components/widgets/spoolman/QRReader.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/components/widgets/spoolman/SpoolmanCard.vue
  src/components/widgets/toolhead/ToolChangeCommands.vue
  src/locales/en.yaml
  src/plugins/filters.ts
  src/plugins/i18n.ts
  src/store/spoolman/actions.ts
  src/store/spoolman/getters.ts
  src/store/spoolman/mutations.ts
  src/store/spoolman/state.ts
  src/store/spoolman/types.ts
  src/util/__tests__/date-time-formatters.spec.ts
  src/util/date-time-formatters.ts
  src/util/string-formatters.ts
Labels: FR - Enhancement

#1331 feat: report target layout in layout edit mode
  src/components/layout/AppBar.vue
  src/globals.ts
  src/locales/de.yaml
  src/locales/en.yaml
Labels: FR - Enhancement

#1640 feat(i18n-JA): update Japanese language
  src/locales/ja.yaml
Labels: UI - Translations

#1647 feat: configurable Klipper Save & Restart action
  src/components/settings/FileEditorSettings.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/server/getters.ts
Labels: FR - Enhancement

#1645 feat(Spoolman): spool progress indicator
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
Labels: FR - Enhancement

#1648 feat: optional history totals in days and kilometers
  src/components/widgets/stats/PrinterStatsCard.vue
  src/components/widgets/thermals/TemperatureTargets.vue
  src/locales/en.yaml
  src/store/config/state.ts
  src/store/config/types.ts
  src/util/date-time-formatters.ts
  src/util/string-formatters.ts
Labels: FR - Enhancement

#1654 fix: incorrect update status on system packages
  src/components/settings/VersionSettings.vue
  src/store/version/getters.ts
Labels: GH - Bug

#1656 feat: download bed mesh image
  src/components/settings/GeneralSettings.vue
  src/components/widgets/bedmesh/BedMeshCard.vue
  src/components/widgets/bedmesh/BedMeshChart.vue
  src/locales/de.yaml
  src/locales/en.yaml
  src/locales/es.yaml
  src/locales/fr.yaml
  src/locales/hu.yaml
  src/locales/it.yaml
  src/locales/ja.yaml
  src/locales/ko.yaml
  src/locales/nl.yaml
  src/locales/pl.yaml
  src/locales/pt.yaml
  src/locales/pt_BR.yaml
  src/locales/ru.yaml
  src/locales/sl.yaml
  src/locales/ta.yaml
  src/locales/tr.yaml
  src/locales/uk.yaml
  src/mixins/files.ts
  src/util/download-url.ts
Labels: FR - Enhancement

#1659 feat: check cards for narrow width
  components.d.ts
  src/components/layout/AppObservedColumn.vue
  src/components/ui/AppBtnCollapseGroup.vue
  src/components/widgets/gcode-preview/GcodePreviewCard.vue
  src/components/widgets/history/PrintHistoryCard.vue
  src/components/widgets/job-queue/JobQueueCard.vue
  src/components/widgets/stats/PrinterStatsCard.vue
  src/components/widgets/thermals/TemperatureCard.vue
  src/components/widgets/thermals/ThermalChart.vue
  src/components/widgets/toolhead/ToolheadCard.vue
  src/views/Dashboard.vue
Labels: FR - Enhancement
