Repository fluidd-core/fluidd, pull requests merged in 2025-04, with the labels that each got.

#1660 feat: show disk info per registered directory
  src/components/widgets/filesystem/FileSystemToolbar.vue
  src/components/widgets/system/DiskUsageCard.vue
  src/components/widgets/system/SdInfoCard.vue
  src/globals.ts
  src/locales/en.yaml
  src/store/files/actions.ts
  src/store/files/getters.ts
  src/store/files/mutations.ts
  src/store/files/state.ts
  src/store/files/types.ts
  src/views/System.vue
Labels: GH - Bug

#1641 feat: Implementation of MMU panel to support single-extruder-multi-material printing using the Happy Hare for any MMU/AFC
  components.d.ts
  public/img/mmu/mmu_3MS.svg
  public/img/mmu/mmu_AngryBeaver.svg
  public/img/mmu/mmu_BoxTurtle.svg
  public/img/mmu/mmu_ERCF.svg
  public/img/mmu/mmu_HappyHare.svg
  public/img/mmu/mmu_NightOwl.svg
  public/img/mmu/mmu_QuattroBox.svg
  public/img/mmu/mmu_Tradrack.svg
  src/App.vue
  src/components/layout/AppSettingsNav.vue
  src/components/settings/MmuSettings.vue
  src/components/widgets/filesystem/FileSystem.vue
  src/components/widgets/mmu/MmuCard.vue
  src/components/widgets/mmu/MmuClogMeter.vue
  src/components/widgets/mmu/MmuControls.vue
  src/components/widgets/mmu/MmuEditGateMapDialog.vue
  src/components/widgets/mmu/MmuEditTtgMapDialog.vue
  src/components/widgets/mmu/MmuFilamentStatus.vue
  src/components/widgets/mmu/MmuGateDialogRow.vue
  src/components/widgets/mmu/MmuGateStatus.vue
  src/components/widgets/mmu/MmuGateSummary.vue
  src/components/widgets/mmu/MmuMachine.vue
  src/components/widgets/mmu/MmuMaintenanceDialog.vue
  src/components/widgets/mmu/MmuRecoverStateDialog.vue
  src/components/widgets/mmu/MmuSettings.vue
  src/components/widgets/mmu/MmuSpool.vue
  src/components/widgets/mmu/MmuTtgMap.vue
  src/components/widgets/mmu/MmuUnit.vue
  src/components/widgets/spoolman/SpoolSelectionDialog.vue
  src/components/widgets/status/PrinterStatusCard.vue
  src/globals.ts
  src/locales/en.yaml
  src/mixins/mmu.ts
  src/store/config/state.ts
  src/store/config/types.ts
  src/store/index.ts
  src/store/layout/state.ts
  src/store/mmu/actions.ts
  src/store/mmu/getters.ts
  src/store/mmu/index.ts
  src/store/mmu/mutations.ts
  src/store/mmu/state.ts
  src/store/mmu/types.ts
  src/store/printer/types.ts
  src/store/spoolman/state.ts
  src/store/spoolman/types.ts
  src/store/types.ts
  src/types/index.ts
  src/types/mmu.ts
  src/views/Dashboard.vue
  src/views/Settings.vue
Labels: FR - Enhancement

#1661 feat(Spoolman): spool progress indicator in card
  src/components/widgets/spoolman/SpoolmanCard.vue
  src/store/spoolman/getters.ts
  src/store/spoolman/types.ts
Labels: FR - Enhancement

#1664 fix: raise click event only once
  src/components/ui/AppBtnToolheadMove.vue
Labels: GH - Bug

#1668 feat: adjustable thumbnail size on Job Queue and History
  src/components/widgets/filesystem/FileSystemBrowser.vue
  src/components/widgets/filesystem/FileSystemToolbar.vue
  src/components/widgets/history/JobHistory.vue
  src/components/widgets/job-queue/JobQueueBrowser.vue
  src/components/widgets/job-queue/JobQueueToolbar.vue
  src/store/config/actions.ts
  src/store/config/mutations.ts
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#1669 feat(JobQueue): use current print ETA in queue ETA
  src/components/widgets/job-queue/JobQueueBrowser.vue
Labels: FR - Enhancement

#1672 feat(Updates): adds python packages support
  src/components/settings/VersionSettings.vue
  src/store/version/getters.ts
  src/store/version/types.ts
Labels: FR - Enhancement

#1676 fix: use path & filename in MmuEditTtgMapDialog
  src/components/widgets/mmu/MmuEditTtgMapDialog.vue
Labels: GH - Bug

#1666 feat: Enhancements to Happy Hare MMU support
  public/img/mmu/mmu_MMX.svg
  src/components/settings/MmuSettings.vue
  src/components/widgets/mmu/MmuCard.vue
  src/components/widgets/mmu/MmuEditGateMapDialog.vue
  src/components/widgets/mmu/MmuFilamentStatus.vue
  src/components/widgets/mmu/MmuMachine.vue
  src/components/widgets/mmu/MmuMaintenanceDialog.vue
  src/components/widgets/mmu/MmuSettings.vue
  src/components/widgets/mmu/MmuSpool.vue
  src/components/widgets/mmu/MmuUnit.vue
  src/locales/en.yaml
  src/mixins/mmu.ts
  src/store/config/state.ts
  src/store/config/types.ts
Labels: FR - Enhancement

#1680 docs: fix typo
  docs/development/index.md
Labels: Docs - Enhancement
